TownyAdvanced/SiegeWar

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/english.yml
This PR changes the global messages in TownPeacefulnessUtil into nation messages so it's not as spammy, and also the very long message that gets sent when a town becomes peaceful or non-peaceful.
Edit: Also fixes an exception I found
____
____
____
=> Some small changes

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/hud/SiegeHUDManager.java, src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/resources/english.yml
This PR adds the /siegewar hud [town] command, similar to the /plot perm hud.
Last PR got messed up, so it's reopened here.
____
____
#3 
____
=> Siegewar Hud #2

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/english.yml
This PR adds and fixes various methods peaceful towns were able to use to enable pvp.
____
PEACEFUL_TOWNS_ALLOWED_TO_TOGGLE_PVP
____
____
=> Fix peaceful towns being able to enable pvp.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
A small fix so that SiegedTowns and SiegedTownNames don't require a server restart to get updated.
____
____
____
=> SiegedTown(Names) will get updated as sieges start/end

src/main/java/com/gmail/goosius/siegewar/Messaging.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/resources/english.yml, src/main/resources/plugin.yml
This PR adds 2 new /siegewaradmin commands: /swa town, and /swa siege, alongside some small fixes.
Exact commands:
/swa siege [town_name] end
/swa siege [town_name] setpoints [points]
/swa town [town_name] setcaptured [true/false]
/swa town [town_name] setplundered [true/false]
____
New permission nodes:
- siegewar.command.siegewaradmin.siege
- siegewar.command.siegewaradmin.town
____
____
=> Added: /swa siege & /swa town commands.

src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java
A small fix so that towns that get toggled peaceful with /townyadmin don't get a counter with 0 days added.
____
____
____
=> Fix peacefuldays metadata being added when it shouldn't.

src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
Useful for #25 
____
____
____
=> Adds Siege#getTimeRemaining() and removes two methods that did similar.

src/main/java/com/gmail/goosius/siegewar/enums/SiegeStatus.java, src/main/resources/english.yml
Will be of use for #25 
____
____
____
=> Adds a translatable name to the SiegeStatus enum.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
This PR fixes the setCaptured and setPlundered commands, towns and sieges will now get saved/modified correctly.
____
____
____
=> Fix setCaptured and setPlundered.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
so we can use the cancellationMsg in the PlotToggleEvent.
____
____
____
=> Bump min. Towny version to 0.96.5.15 

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java
=> Finish TODO regarding using new setCancellationMsg()

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
A small change so that the huds get updated the moment a player dies.
____
____
____
=> add UpdateHUDs to PlayerDeath

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
Adds a check to the basic banner control requirements function to stop players gliding with an elytra from getting control.
____
____
=> Add isGliding check for elytras during a banner control session.

src/main/resources/french.yml
Adding full french translation for the baguette bois
---
=> Adding French Translation

.github/pull_request_template.md
=> Update link to license in pull_request_template.md

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java
also Clean up unused imports.
There was no reason I had 1.16 as the required API, should be no issue to have it on 1.13.
____
____
____
=> Drop the required MC version down to 1.13

src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
This PR fixes siege markers not being removed when the siege itself has ended.
____
____
____
=> Fix markers not being removed properly

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/resources/english.yml
This PR adds the /swa siege [town] command, in order to end a siege instantly with neither side winning.
____
____
____
=> Add /swa siege [town] remove command

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/MetaDataUtil.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Replaces all the TownyUniverse saves with the Town.save() function.
____
____
____
=> Switch to using Town.save()

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
This PR fixes new sieges having their pvp and explosion settings set to true, and not setting these to what is specified in the config.
____
____
____
=> Fix towns having pvp and explosions forced on

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
This PR adds an optional increased cost for sieging capitals by a configurable percentage.
____
Adds WAR_SIEGE_CAPITAL_SIEGE_COST_INCREASE_PERCENTAGE
____
#55 
____
=> Add optional increased cost for sieging capitals

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
This PR adds a function to check if the block a player has placed is at a valid location, and removes an unused parameter
____
____
____
=> Reduce PlaceBlock messages when placing blocks in normal cases

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
also removes one unused import.
____
____
Fixes https://pastebin.com/UFPKPxZy
____
=> Fix ArrayOutOfBounds on empty /sw nation command.

src/main/java/com/gmail/goosius/siegewar/hud/SiegeHUDManager.java
A small change to the hud, so that you don't need to run the command twice if you want to change which siege it's currently displaying. Also prevents an error that can sometimes happen when doing /plot perm hud without disabling the siege hud first.
____
____
____
=> Small hud change

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Fix sending shutting down messages twice.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
=> Fix calling on missing language string.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
Messaging fixes
Closes #84, Closes #85
____
N/A
____
- https://github.com/TownyAdvanced/SiegeWar/issues/84
- https://github.com/TownyAdvanced/SiegeWar/issues/85
____
=> Messaging fixes

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
Remove unused import.
____
____
____
=> Bump required version number to 0.96.7.0.

pom.xml, src/main/resources/english.yml, src/main/resources/french.yml
Add new strings to french.yml.
Move new lang string in english.yml to make updating the file easier.
____
____
____
=> Bump SiegeWar version number for release.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java
Replaces all TownyUniverse saves with the simpler nation.save().
____
____
____
=> Switch to using nation.save() function

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Now 100% less messed up
#89 
____
____
____
=> Disable nation perms when town is invaded

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/MetaDataUtil.java, src/main/java/com/gmail/goosius/siegewar/metadata/NationMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderTown.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java, src/main/resources/english.yml
Adds towns captured/lost, and plunder gains/losses. Removed siege wins/losses
Example screenshot of new statistics:
____
____
____
=> Add more nation statistics

pom.xml
As per title
____
N/A
____
N/A
____
=> Version update to 0.1.1

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java, src/main/resources/plugin.yml
- gathers info from configs to accurately show what can be done on the
given server.
____
New Command: `/sw guide`
- Permission node defaults to true for everyone.
____
Closes #70 
____
=> Adds /sw guide - which opens a guide book GUI.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
=> Take into account that some times the nation delete event can not return a proper king when being removed via safemode prevention.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
Prevents usage of other teleport commands being able to be used to teleport players into siege zones, while it's supposed to be disabled.
____
____
Closes #71 
____
=> Prevent usage of other plugins to teleport into siegezones

src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Will prevent any sort of economy error when the economy couldn't be used even while the config says it should be used.
____
____
____
=> Replace TownySettings.isUsingEconomy() with TownyEconomyHandler.isActive()

pom.xml
- POM update to latest release
____
N/A
____
N/A
____
=> Release 0 2 0

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarCannonsListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java
- Also cleans up unused imports.
____
____
____
=> Allows admins/ops to use their teleport commands in siege areas.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
Bumps the minimum required towny version to 0.96.7.1, because the TownyExplosionDamagesEntityEvent event was moved to the damage package in that version.
____
____
____
=> Bump min. Towny version to 0.96.7.1

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Bump min towny version to 0.96.7.4

src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
Fixes a concurrent modification exception that can sometimes happen when multiple markers are removed at once.
____
____
Closes #151
____
=> Fix possible concurrent modification exception

src/main/java/com/gmail/goosius/siegewar/Messaging.java, src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- Adjusts to the new Towny API calls added in 0.96.7.4.
- Re-jiggers a couple things to use Streams.
____
____
____
=> Remove ignored NotRegisteredExceptions.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
- With current code, plunder (if the attacker activates it), is distributed between the soldiers of the official nation attacker, according to rank.
- However this distribution is not according to merit because:
- Some of the recipients may not even have been at the siege.
- Some of the recipients may have turned up but made minimal contributions.
- No allied soldiers are included.
- Although none of this is strictly unrealistic, that is not the primary concern. The primary concern is that, for many soldiers (particularly allied ones), since they usually get less plunder than their efforts deserve, they are less motivated to show up.
- Also if they do show up, instead of trying to arrange to be paid properly (a shocking idea), some of the more pvp-skilled ones may self-servingly demand …
=> Plunder distribution refactor

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
=> Add beacon preference to SiegeWarHelp

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
As per title
____
N/A
____
N/A
____
=> updated lp glitch mitigation for current ranks

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/PermissionUtil.java
- Renames SiegeWarPermissionUtil to PermissionUtil
- Put the hasTownMilitaryRank and hasNationMilitaryRank into the
PermissionUtil.
- Refactors the military rank lists to Lists we can use in single-line
tests.
____
____
____
=> Refactor PermissionUtil

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- With current code, bc sessions do not pause if there are nearby enemy soldiers who are ALREADY on the bc list
- In this PR I fix that issue to include those soldiers
____
N/A
____
N/A
____
=> Added to bc pause conditions - Nearby enemy soldiers who are on the BC list

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/PermissionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/resources/english.yml
____
- Adds /sw version command.
- Players in spectator can no longer get banner control.
- Silences some errors.
- Removed LP glitch mitigation, since it was no longer required.
____
____
=> Small changes for hotfix

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
Changes:
* Inventory degredation warning gets sent earlier
* Increased the min. durability a bit
* Fixes sw version being incorrectly formatted in the help screen
____
____
____
=> Small changes

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
Small PR with a few fixes relating to the latest Towny version
- Towns under siege cannot merge with other towns anymore
- Removed a few no longer needed try/catches
- Bumped version to 0.3.1 and Towny version to 0.96.7.6
- Lang files bumped to 0.15
____
____
____
=> Town Merge Fix

src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
Fixes a small typo in the guide book.
____
____
____
=> Fix typo in guide book

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
- Added missing listener tag
____
N/A
____
N/A
____
=> Add missing listener tag

src/main/java/com/gmail/goosius/siegewar/hud/SiegeHUDManager.java
Fixes https://pastebin.com/J8dw13BL
____
____
____
=> Fix ConcurrentModificationException possible in HudManager.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
- Fix for death recognition
- This is likely a hotfix thing
____
N/A
____
N/A
____
- [N/A trivial fix] I have tested this pull request for defects on a server. 
=> Fix for siege-death recognition

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
Fixes https://pastebin.com/gi0HcGe2
____
____
____
=> Fix potential class-casting issue.

pom.xml
POM update to 0.3.2
____
Na
____
Na
____
- [Na] I have tested this pull request for defects on a server. 
=> updated pom to 0.3.2

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/resources/plugin.yml
Fixes some harmless but annoying errors. Adds defaults to 3 switch cases, and adds Dynmap-Towny as a softdepend.
____
____
____
=> Fix some harmless errors

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
=> Fix immunity help not being shown sometimes

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
- With current code there is a bug where peaceful towns are not released if their home nation is a non-enemy
____
N/A
____
N/A
____
=> Peaceful town choice fix

src/main/resources/english.yml, src/main/resources/french.yml
- Very small cleanup from last PR
- Removed 2 lang strings which are now unused
____
N/A
____
N/A
____
=> Remove unused lang strings

pom.xml
- Next release will be 0.3.6 (not 0.4.0 as was rpreviously anticipated & as per current master code)
- Updated pom to 0.3.6
____
N/A
____
N/A
____
=> Update pom to 0.3.6

src/main/resources/english.yml, src/main/resources/french.yml
- added version related comment in lang files
____
N/A
____
N/A
____
=> lang_file_comment_update

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Solves the bug by making this change:
```java
case ATTACKERS:
battlePoints = siege.getBannerControllingResidents().size() * SiegeWarSettings.getWarBattlePointsForAttackerOccupation();
battlePoints = SiegeWarScoringUtil.applyBattlePointsAdjustmentForPopulationQuotient(true, battlePoints, siege);
siege.adjustAttackerBattlePoints(battlePoints);
if (!siege.getSiegeType().equals(SiegeType.REVOLT))
siege.registerWinningBattleContributorsFromBannerControl();
break;
case DEFENDERS:
battlePoints = siege.getBannerControllingResidents().size() * SiegeWarSettings.getWarBattlePointsForDefenderOccupation();
battlePoints = SiegeWarScoringUtil.applyBattlePointsAdjustmentForPopulationQuotient(false, battlePoints, siege);
siege.adjustDefenderBattlePoints(battlePoints);
if …
```
=> Fixes plunder under REVOLT siege scenarios

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarAllegianceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
=> Update min. Towny version to 0.97.0.0 and remove NRE and EconomyException catches.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
=> Fixes ScoringUtil Casting exception.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeController.java
number to 0.3.8
____
____
____
=> Fixes using old getNationUUID() methods in the loading. Bumps version

pom.xml
As per title
____
N/A
____
N/A
____
=> Pom update to 0.4.0

src/main/resources/english.yml, src/main/resources/french.yml
- Update lang files as to 0.21
____
N/A
____
N/A
____
=> lang file updates

pom.xml, src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java
- This PR fixes an NPE with regular siege endings
- This fix is targeted for a hotfix release
____
N/A
____
Fixes #312 
____
=> SW-312 Fix NPE Exception with siege ending

src/main/resources/english.yml, src/main/resources/french.yml
=> remove double color code from lang file

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
These changes solve minor issues, along with an NPE while running `/swa siege` subcommands with non-existent towns.
____
____
____
=> Minor optimization and NPE fix

pom.xml
As per title, in prep for imminent pre-release
=> Changed pom to 0.4.6.

src/main/java/com/gmail/goosius/siegewar/Messaging.java, src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarCannonsListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/Settings.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/settings/Translation.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java, src/main/java/com/gmail/goosius/siegewar/utils/FileMgmt.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDynmapUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Also removes unused imports.
____
____
____
=> Removes all println calls that paper has gotten naggy about.

pom.xml, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/resources/english.yml, src/main/resources/french.yml
- Added a missing translation, of something which is currently hardcoded to English
____
N/A
____
Closes #354 
____
=> Sw 354 Adding missing translation

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
Also:
- removes unused imports.
- replaces deprecated TownRuinSettings call.
- minimum Towny version set to 0.97.2.0.
____
____
____
=> Fixes missing method in SiegeWarTownEventListener removed in the status screen update.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
This PR adds more methods to the events thrown at start and end of
sieges.
It also adds a SiegeSide variable to Sieges: SiegeWinner.
____
____
Closes #400.
____
=> Enhance Start and End Siege Events

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/resources/english.yml, src/main/resources/french.yml
=> Add permanent option to /swa revoltimmunity command.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Bump minimum Towny version to 0.97.3.0.

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
=> Fix BattleSession boss bar not updating.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
=> Add SiegeCamps to guide book, bump min. Towny version to 0.97.5.0.

pom.xml, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
=> Upon siege end, finalize active battle session.

pom.xml, src/main/java/com/gmail/goosius/siegewar/settings/CommentedConfiguration.java
=> Fix for spigot 1.18.1 enabling config comments by default.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java
=> Add SiegeController.getSiegeAtLocation(Location)

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/resources/english.yml, src/main/resources/french.yml
=> Fix /sw nextsession command causing an NPE.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- Looks like siegezone glowing is broken. 
- This very small PR fixes the bug.
____
N/A
____
Closes #399 
____
=> Bugfix for glowing

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Removes the allowed-worlds section of the config.
SiegeWar is now enabled/disabled via /tw toggle warallowed.
____
____
____
=> Switch to using TownyWorld#isWarAllowed().

src/main/java/com/gmail/goosius/siegewar/utils/SiegeCampUtil.java
=> Fix Failed SiegeCamp message being broadcast globally.

src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
We were updating the battlesession bar when evaluating the banner capturing sessions.
____
____
Closes #438.
____
=> Remove battle session boss bar from online players.

src/main/resources/english.yml, src/main/resources/french.yml
- Removed 2 unused lang strings
- Re-worded some lang strings, to remove the word "breach", which now has a different meaning.
____
N/A
____
N/A
____
- [ N/A] I have tested this pull request for defects on a server. 
=> Wall- Breaching Lang String Improvements

pom.xml
=> Plugin version bump to 0.7.7

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
____
As per #469 
- The indicated mechanism is convulated, and the reward was probably always too slow to impress its target group, pvp'ers looking for a quick loot fix at the besieged town
- The new Wall Breaching mechanic provides a fix for that group in this area, with generally more of a sense of invading and looting/destroying the town.
- This PR removes the feature
____
Closes #469 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) …
=> Remove Plunder Contributions Feature

src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapIntegration.java
- I noticed a small issue with the logic in the dynmap integration
- In this small PR I fix the issue and centralize some related logic
____
N/A
____
N/A
____
- [  N/A ] I have tested this pull request for defects on a server. 
- I carefully eyeballed this, and I think it will be ok
=> Dynmap Integration Fix

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
- A longstanding problem during sieges (and outside them) is player "block glitching" their way through walls, or over them.
- This is a particular problem in the current pre-release series, and for the next full release, because:
- Bonus points can be now be gained for getting past walls.
- Peaceful town residents are no longer safe from PVP if someone gets inside their town.
- This PR adds a prevention for two of the most common types of glitching:
- Glitching by placing blocks (e.g pillaring)
- Glitching by breaking blocks (e.g. getting through a door)
- The prevention works by teleporting a player back to where they were when their break/place attempt was denied.
- To avoid the possibility of server lag, the teleporting is cached, so that each player is tp'd a maximum of once per 500 …
=> Anti-Block-Glitching

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
Misc bug fixes for a few unreleased issues
____
N/A
____
N/A
____
]
=> Misc Bug Fixes

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
- As per title
- A few bits were not removed and causing compilation error.
____
N/A
____
N/A
____
=> Removed some remaining bat-observer stuff

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
=> Clean up unused imports, suppress unused methods that may return.

src/main/resources/lang/en-US.yml
As per title
____
N/A
____
N/A
____
=> Lang file version bump

pom.xml, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/Settings.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java, src/main/resources/config-migration.json
- Added an out-of-box-usable suite of artefacts
- Special thanks to **ItsJules** for designing most of the Artefacts!!!!
- Also made it easier for users to configure artefacts
- Also made it easy for TA to update the default artefacts
- Also gave in to the inevitable and set POM to 0.7.16  (back from a prospective 0.8.0)
____
```
DOMINATION_AWARDS(
"domination_awards",
"",
"",
"",
"############################################################",
"# +------------------------------------------------------+ #",
"# |                  DOMINATION AWARDS                   | #",
"# +------------------------------------------------------+ #",
"############################################################",
""),
DOMINATION_AWARDS_ARTEFACT_OFFERS(
"domination_awards.artefact_offers",
"",
"",
"",
"# …
```
=> Add Usable Artefact Suite

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
The `isArtefact` and `isExpiredArtefact` methods in the SiegeWarDominationAwards class begin by checking if `ItemStack#getItemMeta` is null. Then they call `ItemStack#getItemMeta` again to check the item's PDC.
Internally, `ItemStack#getItemMeta` clones the `ItemMeta` of an `ItemStack`. This becomes expensive when checking large numbers of items. I replaced the `ItemStack#getItemMeta` null check with `ItemStack#hasItemMeta` which simply checks if the meta is null without cloning it.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and …
=> Optimize artefact check

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/events/GlobalDominationAwardsEvent.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
- This PR adds an event for the Domination awards
- Also it allows "giveglobal" to work regardless of previous records
____
N/A
____
Closes #581
Closes #586
____
=> Domination awards event

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- With current code an "uknown method" error appears on startup 
- Some servers apparently cannot find PotionEffectType.getByKey()
- I believe they can find getByName().....so I switched to this
____
N/A
____
N/A
____
- [ x ] I have tested this pull request for defects on a server. 
=> Fix for unknown method error

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Fixes this from potentially happening: https://pastebin.com/s21gtruP
____
____
____
=> Fix for when ItemStack has no ItemMeta and we check if it is an Artefact.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/resources/lang/en-US.yml, src/main/resources/plugin.yml
Adds the given number of hours to all sieges, in case of downtime or
maintenance that disrupted normal gameplay.
Also fixes up /swa permission checks to match the current commands.
____
____
Closes #616.
____
=> Add /swa siegeduration addhours # command.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarImmunityUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Just hides logic behind more readable method names.
Touches on a couple of Util classes as well.
____
____
____
=> Refactor on PlaceBlock class to improve readability.

src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java
=> Refactor InvadeTown for readability.

src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java
=> Refactor PeacefullySubvertTown for readability.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java
While refactoring I noticed it can delete the town and still try to act
on the town's name and nation. This should be no longer be possible.
____
____
____
=> Refactor PlunderTown for readability and safety.

src/main/java/com/gmail/goosius/siegewar/playeractions/StartSuppressionSiege.java
=> Refactor StartSuppressionSiege for readability.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartLiberationSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java
=> Refactor Conquest, Revolt and Liberation SiegeStarters

src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullyRevolt.java
=> Refactor PeacefullyRevolt for readability.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartLiberationSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartSuppressionSiege.java
=> Unify SiegeCamp starting process from the StartSiege classes into the SiegeController.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
=> Prevent double messaging of SiegeWar announcements.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
=> Refactor the BukkitEventListener and PlayerDeath classes

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Fix npe seen in startup when last run version is null.

src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
=> Use Locale.ROOT when parsing the days of the week.

src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java
Fixes the occupation controller using Collections.singleton, which causes an exception when it tries to add another town to that set
____
=> Fix occupation controller using Collections.singleton

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
=> Adapt to NationLevel change in Towny. Min Towny version 0.98.3.4.

src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
=> Fix Siege Assembly banners being breakable.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/resources/lang/en-US.yml
=> Stop a town from being the victim of multiple siege assemblies.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Allows for other plugins to easily determine if there's a SiegeCamp/SiegeAssembly in a given location.
____
____
Closes #669.
____
=> Add isLocationInActiveSiegeAssembly to SiegeWarDistanceUtil

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
=> Update Towny min. Version to 0.98.4.0 & adapt to changes.

src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
Siege receives three methods:
- isDefenderWinning()
- isAttackerWinning()
- getSeigeWinnerFormatted()
____
____
Closes #674.
____
=> Add convenience methods to Siege.

.github/workflows/deploy_release.yml
=> initialize deploy_release.yml

.github/workflows/deploy_release.yml
=> workflow: implement deploy_release 

.github/workflows/deploy_release.yml, pom.xml
Adds Towny's version as a pom property,
use said property to autofill release page.
____
____
____
=> Make deploy_release workflow smarter

src/main/java/com/gmail/goosius/siegewar/events/PreSubvertTownEvent.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java
Event thrown when SiegeWar is about to process a peaceful town becoming occupied by a nation.
____
____
____
=> API: New PreSubvertTownEvent

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
Times were being rendered as a number of days/hours/seconds instead of a time stamp.
____
____
____
=> Fix incorrect times being rendered on ally/rank/town removal messages.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Fix the ascii art not colouring.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Update Min. Towny Version to 0.98.6.0.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/resources/lang/en-US.yml
Towns which are not allowed to war cannot be sieged or start sieges.
____
____
____
=> Add support for isAllowedToWar Town setting, compatibility with TownyCaptureSites.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
=> Replace deprecated Towny method.

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeCampUtil.java
=> Actually repair broken failedSiegeCamp metadata.

pom.xml, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
=> Fix military salary not being paid correctly.

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
=> Add cost of siege to the error message when players cannot afford a siege.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
____
New Config Node: war.siege.money.plunder.plunder_paid_over_time
- Default: false.
- When true, plunder will function differently, when a town cannot afford to pay the full plunder costs.
- Initially the money is paid to the plunderer in full, from either the Towny server-account (used in closed_economies), or else from thin air.
- The money is then paid back on a daily basis from the plundered town, using the set number of days.
- The goal of this system is to make sure that attackers get paid, while giving plundered towns a chance to pay their debt over time.
New Config Node: war.siege.money.plunder.number_of_payments
- Default: 7
- When plunder_paid_over_time is true, how many days will the plunder debt be paid over?
____
Closes #691 
____
By making this pull request, I represent …
=> Add new (optional) plunder debt system.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
=> Fix distance test that can create cross-temporal siege zones. (Spooky)

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Previously, the daily plunder debt only took effect if the town could not immediately pay the plunder costs.
____
____
____
=> Make optional plunder debt spread out over days work even when towns could pay.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
Taken off of the Occupation_Refactor PR.
____
____
____
=> (Re-)Add Nation Refunding.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/DataCleanupUtil.java
- Make occupied towns immune to the regular nation tax, as they instead pay the nation occupation tax.
- Note: I tested this and confirmed that the messaging works ok e.g. the town gets a nice message of "Your town was exempt from the nation tax"
____
____
____
=> Make occupied towns immune to regular nation tax

src/main/java/com/gmail/goosius/siegewar/utils/PermsCleanupUtil.java
Replaces previous logic which could result in a
previously-positively-set success value being overridden by a later negative success.
____
____
____
=> Fix PermsCleanupUtil's success logic so that the townyperms.yml is saved more reliably.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarAllegianceUtil.java
- Get rid of "HomeDefenceWar" stuff in SiegeController
- Get rid of the unused methods in SiegeWarAllegianceUtil
- SiegeWarStatusScreenListener Line 303 logic not needed
____
____
____
=> Removed some unused methods & logic

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- Some minor nonfunctional cleanups in BC util
____
____
____
- [ NA too trivial ] I have tested this pull request for defects on a server. 
=> Minor Cleanups in BC-Util

src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
- The "Siege Observers" feature was removed some time ago
- However little bits of code were left over from that, which are no longer used (certainly they are not supposed to be being used)
- This PR removes the unused code & comments
____
____
____
=> Remove unused siege-observers code & comments

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/objects/SiegeCamp.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
- With current code, there are occasional fake sieges started to grant immunity, either by allies or by new nations specifically set up for this.
- This PR provides a simple feature to deter such sieges, by adding a new upfront, sunken cost, to starting a siege.
- Note that these sieges can never be fully prevented programmatically, but this might help.
- The feature is optional, due to the fact that it will remove money from the economy.
____
```
upfront_cost_per_plot: '0.0'
```
____
Closes #642 - The stated reason for this ticket was to discourage fake sieges. Although the ticket proposes a solution of a nation siege timer, which might be effective against one specific type of fake siege, this ticket is deemed to provide a more effective and general solution with fewer side effects, and …
=> Add Feature: Upfront siege cost

src/main/resources/lang/en-US.yml
- Typo fix around this feature
____
____
____
=> Typo fix around "swa set immunities"

src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapIntegration.java, src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapTownyListener.java, src/main/resources/lang/en-US.yml
- Cleaned up some code related to the dynmap/towny-dynmap integrations
____
____
____
=> Dynmap integration cleanups

src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapTownyListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java, src/main/java/com/gmail/goosius/siegewar/utils/DataCleanupUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java
- With current code, SW 2.0.0 would break TownyResources, due to some renamings and method deletions
- Since SW 2.0.0 is big enough already, this PR allows SW 2.0.0 to be deployed without breaking existing TownyResources plugins.
- There are only 2 functional changes in this PR, which are very low risk:
- Refactor-Moved SiegeWarTownOccupationUtil  ---> TownOccupationController
- Added back one method in TownOccupationController:  getOccupiedForeignTowns()
____
____
____
- [N/A very low risk ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
=> Fix TownyResources Integration

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/resources/lang/en-US.yml
- With current code, some SW timers on the town screen take up lots of space and are not neatly placed
- The PR fixes these issues, so that all SW town screen timers, whenever they are needed, are now include in hover items. Example: 
____
____
____
=> Improved Apperance of Town Screen SW timers

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- With current code, a translation key is not found
____
____
____
=> Fixed translation key

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarInventoryUtil.java
- A welcome re-addition I'm sure!
- Basically a copy pasta of the keep-inventory code from TownyCombat, except that this version applies in siegezones, and does not have keep-experience .... which both unnecessarily complicates things, and is open to a subtle exploit from players mutually killing each other in siegezones to gain experience.
____
____
____
=> Re-Add Keep-inventory-in-siegezones

src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderTimedWin.java, src/main/resources/lang/en-US.yml
- Add plunder-reduction-on-close-attacker win
- This PR also changes the configged percentage reduction values to integers
____
____
____
=> Add close-win plunder reduction

src/main/java/com/gmail/goosius/siegewar/SiegeWarAPI.java, src/main/resources/lang/en-US.yml
Some is boilerplate SiegeController/SiegeWarDistanceUtil, in addition to this is various getSiege methods for people's taste.
TODO: 
____
____
____
=> Add SiegeWarAPI class, for external developers.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarNationSetOccupationTaxAddonCommand.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java
On top of removing unused imports, this PR replaces one occurance of using a deprecated method, and replaces a now-redundant re-colouring of a town's nation map colour (the colour is already set on Event launch to what we would be setting it to in the EventHandler.)
____
____
____
=> Cleanup unused imports, unneeded code.

src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java
- Bugfix as per title
____
____
____
- [N/a too trivial] I have tested this pull request for defects on a server. 
=> Bugfix - Stop plunder on defender close win

src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/resources/lang/en-US.yml
Fixed the following minor issues:
- Adjust BC message........says I can be 4 blocks below, but then not below....
- Getting message on newday, "your nation collection occupation taxes worth 0.00".  
- msg_err_town_already_invaded ---  translation missing
- On nation screen, linked the stats to the correct "enable/disable" config
- On nation screen, put "War History" at the start (because this is more permanent), then sieges
____
____
____
- [N/A should be low risk ] I have tested this pull request for defects on a server.  …
=> Minor Bug Fixes

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- Adjusted default occupation tax to 1 per plot
- I think this fits better with the other default values, and in any case is even easier to calculate for servers/nations wondering how much it will bring in.
____
____
____
=> Changed default occ tax

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/resources/lang/en-US.yml
- With current code, the banner capture distances are somewhat complex .... e.g. there are separately configured up, down, and horizontal distances, then the trap mitigation has additional restrictions.
- As per the "simple/fun/usable" theme of SW 2.0.0, this PR simplifies the situation:
- Now, if trap mitigation is off, you simply have to stay within 16 blocks of the banner and out of the town
- If trap mitigation is on, you also have to stay below the banner altitude 
- This PR also removes the warning about flying, from the BC instructions, and the BC fail message. Because on SW servers this seems to be an extremely uncommon ability in siegezones, thus it should suffice for this to be covered in the github user guide.
____
____
____
- [N/A too trivial ] I have tested this pull request …
=> Simplify Banner Control Distances

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/lang/en-US.yml
A few minor fixes:
[Adjusted default new town immunity to 7 days](https://github.com/TownyAdvanced/SiegeWar/commit/8009524f2085fff9ddebcae943b07a67a666eef0)
[Fixed bug where partial warchest was returning on decisive wins](https://github.com/TownyAdvanced/SiegeWar/commit/abf802b2d5de075c3bfb12f0eeae12a1814462dd)
[Fixed distance calculation problem ... and a Towny bug ticket might be indicated](https://github.com/TownyAdvanced/SiegeWar/commit/85098c9c120eb331c932ea11ad3c5a971e571c8a)
[Fixed full warsickness occurring in besieged towns](https://github.com/TownyAdvanced/SiegeWar/commit/2311f545583ba5af8c8455492bd36287fe22e392)
[Fixed typo in lang strings](https://github.com/TownyAdvanced/SiegeWar/commit/b811b72cf76ad2a86fc55055a642ef9d66ee78bf)
Fixed another typo in lang string
____
____ …
=> Misc Fixes for SW2.0.0

src/main/resources/lang/en-US.yml
- As per discord convo, removed the "heroic efforts" type language for close victories, as the efforts would not necessarily be heroic.
____
____
____
=> renames lang strings

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- In keeping with the low-toxicity/low-stakes theme of SW 2.1.0, this PR reduces the default on-death-tools-degrade from 20% to 5%.
____
____
____
=> Reduce default tools-degrade-on-death from 20% to 5%.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
- Misc fixes
- Moved the warning about configs, until after the economy-money has been calculated
- Fixed the "tell disabled" message
____
____
____
=> Final 210 fixes

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/NationMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
=> Clean up unused imports.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
=> Fix /sw nation command used with no arguments.

pom.xml, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarWarningsUtil.java, src/main/resources/lang/en-US.yml
- With current code, the "Bad Config Warnings" feature will likely give incorrect warnings on many servers.
- This is because the feature does not account for "test/debug towns", and the large bank balances they often have.
- This PR fixes the problem by adding a note to the config blurb, and also an automatically generated note, to inform server owners about this limitation.
- This PR also changes the name of the config, to automatically re-enable the feature for those server owners who thought it was malfunctioning, and already turned it off.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
=> Added note to warnings about test towns

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/resources/lang/en-US.yml
- With current code, siege banner can be anywhere in a wildnerss chunk which is adjacent to a town
- This tends to make defensive fortifications ineffective, because given sensible banner placement (_16 from town_) and safely offset fortifications (_back by 10_), the banner might be about 26 blocks from the walls, allowing attackers at the banner to hang out about 36 blocks from the walls (_10 from the banner_).
- Since SW never intended to make fortifications irrelevant, this PR resolves the issue, by forcing the banner to be right next to the enemy town. This puts the banner a much more appetizing 10 block from the walls, with attackers at the banner hanging out at around 20 blocks from the walls.
- Note: This is not a free lunch for defenders, because as of SW2.0.0, the defender got a …
=> Move siege banner closer to Town

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- Fixed bug where the progress of "pending" sieges was not saving ... then if the server restarted it would go back to its old value
____
____
Closes #837
____
=> Fix siege progress on pending sieges

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
- The peaceful town public spawn feature won't work until Towny is updated to 0.99.0.8
- This PR updates the required towny ver to 0.99.0.8
____
N/A
____
N/A
____
=> Bump required towny ver to 0.99.0.8

pom.xml
=> Update min towny version for the release workflow.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeCampUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/plugin.yml
Bukkit and Folia supported via Towny's TaskScheduler.
Bump min. Towny version to 0.99.1.0, change version checker to modern option.
Bump SiegeWar version to 2.6.0 because of new Feature.
____
____
Closes #842 
____
=> Add support for Folia servers.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Fix hex colouring of ASCII art.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleCommanderUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSpawnUtil.java, src/main/resources/lang/en-US.yml, src/main/resources/plugin.yml
- With current code, the SW integration with *TownyProvinces* has an issue ---> because players cannot reliably use their preferred meta of having a siege town near to the besieged town.
- The PR resolves the issue by adding the concept of "Battle Commanders"
- Each battle session, 2 are assigned for each Siege, on on each team.
- During that battle session, other participants can run "/sw siege <town>" to spawn on the battle commander
____
```
Permission node: "siegewar.command.siegewar.spawn"
Config Option
############################################################
############################################################
battle_commanders:
enabled: 'true'
````
____
Closes #849
____
By making this pull request, I represent that I have the right to waive copyright and related rights …
=> Battle Commanders / Mobile Spawn Points

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleCommanderUtil.java
- Hotfix for battle commanders not being assigned properly
____
N/A
____
N/A
____
=> Hotfix for battle commanders assignment

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyChatEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
- Currently SW experiences errors if TC is not present
- Fix it so that there's no errors even if TC is not present
____
- NA
____
Closes #861 
____
=> Remove hard dependancy on TC

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Fixes #858
____
NA
____
Closes #858
____
- [NA too trivial] I have tested this pull request for defects on a server. 
=> Added logic so that money is not calculated if economy is missing

pom.xml
As per title
____
na
____
na
____
- [NA too trivial ] I have tested this pull request for defects on a server. 
=> POM update to 2.7.0

README.md
=> Update README.md with jitpack link

src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapIntegration.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
=> Make dynmap layer name configurable.

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
A call to use Towny's scheduler caused a task creation to not be replaced during the update for folia support.
____
____
Closes #898.
____
=> Fix scheduler call that causes issues on folia.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Take care of deprecations.
____
____
____
=> Update min. Towny version to 0.100.1.0.

pom.xml
=> Bump Version Number

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java
=> Fix un-parsed Component codes appearing in the hover component of Siege statuses.

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java, src/main/resources/lang/en-US.yml
=> Purge the use of msg_err_action_disable lang string, replacing all uses with more useful, more detailed error messages.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
=> Bump min. Towny version to 0.100.3.0.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java
=> Fix potential NPE in SiegeWinner in SiegeRemoveEvent.

src/main/java/com/gmail/goosius/siegewar/events/BannerControlSessionStartedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/TownPlunderedEvent.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
=> Add BannerControlSessionStartedEvent & TownPlunderedEvent

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
=> Fix compile error

src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/resources/lang/en-US.yml
=> Allow for customization of HUD title

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
=> Bump Min Towny version to 0.100.4.0.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/resources/lang/en-US.yml
=> Fix nation help lang strings overriding Towny

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarLoreListener.java
=> Fix Lore banner accessing world async at Siege End.

pom.xml
=> Bump version number for release.

.github/workflows/deploy_release.yml
=> Update deploy_release.yml to use Java 21

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSpawnUtil.java
Allows it to be run on Folia servers.
____
____
____
=> Fix /sw spawn using non-async teleport.

jitpack.yml
=> Add jitpack.yml so that SW builds on Java 21 on jitpack.

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeRemoveReason.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/resources/lang/en-US.yml
This PR improves the clarity of the webhook message when a siege is removed by providing the reason of the removal explicitly. Without these changes, the message is always "Siege of X was removed via admin commands." despite the possibility of another reason for the siege removal.
____
N/A
____
N/A
____
=> Add siege remove reason to improve webhook message

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java
This PR removes the copy pasted method in favor of the newly (2 years) public Towny one.
____
N/A
____
N/A
____
=> Remove copied method in favor of Towny counterpart

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
=> Fix BannerControlSessionPreStartEvent thrown async.

pom.xml, src/main/java/com/gmail/goosius/siegewar/events/BannerControlSessionPreStartEvent.java
____
____
Closes #966
Closes #967
____
=> Actually fix new event thrown async.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeController.java
Under an as-of-yet unknown scenario an active siege managed to have no flag block location, resulting in a very large log.
____
____
____
=> Fix null SiegeWar flag block locations spamming the log.

pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionEndedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionStartedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeCampStartEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSafeModeListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
- Bump min. Towny version to 0.101.2.5.
____
____
____
=> Adapt to Towny's switch-over to Paper from Spigot.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/resources/lang/en-US.yml
Note: Still in draft state, not ready for review until #980 is merged
Fixes a possible occupation-escape exploit
____
N/A
____
Closes #910 
____
- [ N/A seems simple enough to be ok ] I have tested this pull request for defects on a server. 
=> Fix possible occupation-escape exploit via merge

pom.xml
=> Bump version to 3.0.0

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
Minor messaging fix
____
N/A
____
N/A
____
- [ NA too trivial ] I have tested this pull request for defects on a server. 
=> Minor messaging fix
