pom.xml, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/resources/Changelog.txt, src/main/resources/plugin.yml
- Adds internal support for Dynmap-Towny features present in Goosius'
fork of Dynmap-Towny.
- Sieges will show on your dynmap, if dynmap is installed.
Dynmap-Towny is not required.
- Information can be seen about the siege including points, banner
control side, warchest.
- Closes #4.
____
____
Closes #4 
____
=> Adds internal support for Dynmap-Towny features present in Goosius' fork of Dynmap-Towny.

.gitignore, src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/resources/english.yml
- Removed the restrictions of having to place an attack banner above ground, or having to be above ground to get a banner control session
- This feature was a legacy feature which was too exploitable and not fun e.g, the enemy could prevent or interrupt banner control sessions by placeing hard-to-see blocks high above the siege zone
- Also the feature is not needed now that the glow-during-sessions feature has been confirmed to be working fine.
____
NA
____
NA
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny …
=> Remove under a block restriction

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/resources/english.yml
- With current code, the "revolt" feature is only applied to towns which are officially "occupied"
- But this was never the intention. For example, the state of Texas does not consider itself "occuped", but if it broke away tomorrow from the U.S., it would most certainly be considered a "revolt".
- Perhaps this update went in at some point in the past due to a misleading message in the english.yml, which I have now fixed in this PR, which used to refer to "occupying power", which was only meant in a metaphorical way, not literally occupied=true.
____
NA
____
NA
____
- [ x] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related …
=> Fixed revolt feature to apply to all towns

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
- Currently an exploit exists where a player can get themselves directly above a siegezone (e.g. like y=250), where they can then drop siege-restricted blocks onto the siegezone (e.g. maybe lava)
- This PR fixes the exploit by making siegezones cylindrical rather than spherical, i.e. ignoring the vertical axis and instead taking in blocks at all heights as long as they are within the horizontal radius.
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny …
=> Make siegezones cylindrical

src/main/java/com/gmail/goosius/siegewar/Messaging.java
- With current code null pointer exceptions can occur when the recipient of a message is an NPC or offline player
- This small PR fixes the problem by checking for a live player before sending the message
____
N/A
____
N/A
____
- [ x] I have tested this pull request for defects on a server. 
- 
=> Fixed null pointers on message npc's/offline_players

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java
- The "leadership aura" feature is extra complexity without any added value
- There is already an implicit leadership aura at work during battles, i.e. when players with actual leadership qualities are doing their thing, so an explicit dynamic points change is unnecessary to get the required effect. 
- By removing the feature, it also makes space for servers to enable much more usefully complex features such as the counterratack booster. 
- I checked with the testers channel and confirmed that this feature is not generally considered useful, and is already turned off on multiple servers.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my …
=> Remove leadership aura feature

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDynmapUtil.java
- The "Tactical Invisibility" feature is simple to use, and essential for standard military tactics like ambushes.
- However the terminology is a real mouthful, which may explain why it is a less popularly discussed tactic than it should be. 
- Thus in this PR I change the terminology to "Map Sneaking"
- I have also updated the relevant wiki documentation
- This PR was all refactor-renames of variables/methods, and renames in configs/comments. No functionality was changed (and I even left the metadata name unchanged)
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
=> Changed terminology of "tactical invisibility" to "map sneaking"

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/resources/english.yml
Fixes items being able to go into negative durability. Instead of items going into negative durability or breaking, durability will be set to 10 or the current durability (whichever is lowest), and send a warning message to the player.
____
____
____
=> Negative item durability fix

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java
- There exists today a big siege balance problem, which many servers are facing.
- It relates to the fact that, with the default death/timed points, large unskilled armies can completely dominate smaller pvp-skilled armies during sieges
EXAMPLE 1
- The following chart shows how much time it takes for 2 siege sides to recover the points from each soldier death, using the default death/timed-point settings (Death points 150, Timed points 10):
```
Player_on_bc	1_Def_Death	Def_Recovery_Time(If BC holds) 	1_Att_death	Att_Recovery_Time(If they switch BC) 	
1		+150		5 mins				-150		5 mins
2  		+150  		2.5 mins			-150		2.5 mins
5  		+150  		1 min				-150		1 min
10  		+150  		0.5 mins			-150		0.5 mins
20  		+150  		0.25 mins			-150		0.25 mins
30  		+150  		0.16 mins			-150		0.16 mins
```
- The …
=> Change counter-attack booster default to active

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/resources/english.yml
- Currently occupied towns can surrender, which can get a little exploity as explained here: https://github.com/TownyAdvanced/SiegeWar/issues/49
- Also wall banners can currently start/end sieges  (but should be only standing banners)
- In this PR I fix both these issues
____
N/A
____
https://github.com/TownyAdvanced/SiegeWar/issues/49
____
=> Fixes for occupied town surrender & wall banners

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
This PR fixes players being given a warning when they die in a siege zone with non-damageable items, and removes their banner control session (if they had any).
____
____
____
=> Inventory degrade fix.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
Currently when a player fails their banner control, they will still have the glowing effect, this PR changes that by removing the glowing effect when a player fails their session.
____
____
____
=> Remove glowing effect when player fails banner control

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/Settings.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Notably, the enabled-worlds-list but also including the forbidden
blocks/buckets and map-sneaking-combinations lists.
Does away with the enabled-worlds method in SiegeWarDistanceUtil, and
queries SiegeWarSettings directly in the two places where the world was
being tested for.
____
____
____
=> Fix config not properly reloading 4 variables.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- I know of no server which actually leaves the default attacks per nation config at 999
- This value is way too high for a sensible default
- To achieve a more useful default I have updated the default value to around where servers tend to set it, at 3
N/A
____
N/A
____
=> Adjusted default config value of max sieges per nation to 3

src/main/resources/plugin.yml
=> Fix hud permission node not being give to everyone by default.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Adds a config option for enabling/disabling the public spawn peaceful towns have (true by default).
____
Adds PEACEFUL_TOWNS_PUBLIC_SPAWNING
____
____
=> Peacefultown teleport config

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- The default configuration for map-sneak items is problematic, because it excludes resource gatherers, which discourages servers from turning off the dynmap setting for invis-if-underground, which is bad for sieges.
- Thus in this PR I adjust the map-sneak items so that resource gatherers can use them
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) for …
=> Adjusted default config for map sneak combos

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
- Generally, guardian towns must not be allowed to hold onto peaceful towns if they get sieged
- This is because, it would allow the exploit of a nation setting up multiple peaceful towns with a dummy guardian town nearby, then getting a friend nation to constantly attack the dummy town, giving it immunity, thus giving the peaceful towns constant immunity
- The current code addresses this exploit by releasing the peaceful towns for both the active siege AND inactive part of the guardian-town siege.
- I think this is overly harsh on the peaceful towns though, and also gives enemies too much leverage
- Thus in this PR, I adjust the code so that peaceful towns are released only for the ACTIVE part of the siege, and can rejoin the guardian town's nation if the defenders are victorious.
- This …
=> Adjusted guardian town requirement

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/english.yml
- With the current code, peaceful towns which are isolated on the map (i.e. far away from any other towns), cannot join a nation at all.  (or are kicked at each new day).
- This is a pointless restriction, which doesn't benefit anyone (i.e. with or without the restriction, a conqueror must do the same thing to capture it i.e. build a colony town nearby), and keeps these towns from closer integration with the server community.
- With this PR I allow peaceful towns to freely join nations if there are no guardian towns nearby
- The peaceful town allegiance rules then become:
```
* If there are no guardian towns nearby - Town has free choice of nation
* If there are guardian town(s) nearby, and 1 or more are NOT under siege - Town must choose the nation of one of those towns
* If there are …
```
=> Add free nation choice for isolated peaceful towns

src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java
Fixes resident metadata not being set if the resident has the refundamount metadata
____
____
____
=> Fix resident nation-refund-amount not being set properly all of the time.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/MetaDataUtil.java, src/main/java/com/gmail/goosius/siegewar/metadata/NationMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java, src/main/resources/english.yml, src/main/resources/plugin.yml
Adds siege wins/losses and enemy nations defeated statistics to /n's
Example: 
Also adds some admin commands to change these statistics manually.
____
____
____
=> Add Siegewar statistics to nation status screens

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/FileMgmt.java, src/main/resources/english.yml
Fixes nations being able to remove nations as enemies while they're sieging them. 
____
____
____
=> Stop nations from removing nations they're sieging as enemies

src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
=> Fix incorrect time showing in the hud for ended sieges.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
Adds leaves and 1.16 tree blocks as unstable blocks, to make sure the banner isn't destroyed (either via other plugins, or leaves disappearing).
____
____
Closes #98 
____
=> Add more "unstable" blocks which the banner can't be placed on

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Adds a new option for spawning a firework rocket at the location of a player when they die inside a siege zone
____
Adds WAR_SIEGE_DEATH_SPAWN_FIREWORK
____
____
=> Spawn firework rocket when a player dies inside siege zone

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
This PR will make it so the nation refund is available under more types
of deletion. Single-town nations being deleted were likely to not
register the king properly. By using the PreDeleteNationEvent, on
monitor priority with canceled events ignored, we will be able to get
the King (probably) every time.
____
____
____
=> Fix nation deletion listener using PreDeleteNationEvent.

src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
- With current code, if a siege is abandoned/surrendered while a banner control session is in progress, the session remains in memory (but not accessed) until the siege object is deleted (within a few days). Generally this doesn't seem to have any negative impacts, except for one - the dynmap icon logic does not realize the fighting is over, and continues to show the "battle" icon (i.e. crossed swords) until the active phase of the siege ends (within 24 hours).
- This is not appropriate. If a siege is abandoned/surrendered, it should still show the fire icon (because siege effects still apply), but not the battle icon, because in almost all scenarios there will be no significant battle there.
N/A
____
N/A
____
- [N/A] I have tested this pull request for defects …
=> Fixed issue where abandoned sieges were still showing as swords on dynmap

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
Fixes an NPE that occurs when a town that has a plot group toggles peacefulness.
____
____
Closes #116 
____
=> Fix setTownFlags NPE

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
Similar to #117, but I forgot that disableNationPerms was also using plot group stuff.
____
____
____
=> Fix NPE when invading a town with a plot group

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
- With current code, guardian towns only qualify if the nation is open
- Therefore on many servers, most of the top nations remain open, in order to pull in peaceful towns.
- Generally speaking, this is ok (if a little messy for nation membership control)
- However, it does open one clear exploit, because if a nation wishes to attack another, then it can found a new battle town close to the target town, have the battle town temporarily join the (open) enemy nation, and then expand the battle town claims right up to the target town, at which point it can rejoin the home nation and a siege can be started.
- Thus by using an exploit, battle towns can be brought much closer to target towns than they should be.
- This PR makes guardian towns qualify not on nation-openness, but instead on …
=> Prevent Nations from exploiting Peaceful-Town-Mechanics to create too-close battle-towns

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
- Currently on the nation screen, ended sieges show up on the attacks list (but not on the defences list)
- Originally both lists showed all sieges, in order to remind nations of recent attack sieges so they wouldn't forget to capture and plunder if they win.
- But it turns out this is not-intuitive to look at - players only expect to see the active ones. 
- Also those nations are probably generally unlikely to forget, and they usually have more than a week's allowance to remember before the ended sieges disappear.
- In this PR I adjust the attacks list to show only active sieges.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions …
=> Nation Screen - Remove ended sieges from siege attacks list

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- Adjusted default config for equipment degrade
- With current value, soldiers have effectively 9 lives per god set. This is too high and sometimes results in overlong battles  (Unlike first person shooters Siegewar does not have real battle ending every 30 mins or so.  Battle sessions help but are not a full break for players because the battle is still ongoing while they are away).
- With adjusted value, soldiers have effectively 4 lives per god set.  This strikes a balance between giving up-and-coming nations a chance, and preventing battles going on too long.
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all …
=> Adjustment to default equipment-degrade config

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
- With current code the `war.siege.switches.non_resident_spawn_into_siegezones_or_besieged_towns_disabled` config affects short distance teleports such as enderpearls and chorus fruit
- This was never the intention of the config, it is just supposed to limit long distance spawning such a /n spawn, /t spawn, tpa, or /home
- Thus in this PR I remove ender pearls and chorus fruit from being affected by this particular config/
____
N/A
____
N/A
____ …
=> Remove ender pearl and chorus fruit from spawn restriction

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
- With current SiegeWar configs, a critical, yet not-initially-noticeable problem can be introduced
- The problem occurs if a server owner sets the banner-control-horizontal distance to greater than the Towny tonwnblock size
- This allows defenders to safely cap from behind their own walls, breaking a core mechanic
- This PR solves the issue by simply linking the horizontal cap distance to the Towny townblock size, which is probably what 99.9% of server owners need anyway, while also making is impossible for server admins to trigger the indicated problem.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all …
=> Fixed horizontal distance to Towny TownyBlock size

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
Small change so any TeleportCause that isn't plugin or command doesn't get blocked.
____
____
Closes #136 
____
=> Allow non-plugin related causes to teleport players into siegezones

src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java
- With current code, on siege attack the system checks for peaceful towns even if the peaceful towns feature is disabled
- It should not do this
- This PR removes that validation
____
N/A
____
N/A
____
=> Removed peaceful towns attack validation check when peaceful.towns=disabled

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
- With current code, if a town happens to have an active cannon session when the siege ends, the explosions remain on.
- This is not desirable - explosion protections should automatically go back on, just like PVP protections.
- With this PR, I fix the issue.
____
N/A
____
N/A
____
=> Cannons Integration - Turn town explosions off after siege

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
A small change so that the glowing effect gets removed when a player quits.
____
____
____
=> Remove glowing when player leaves the game

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/GlassColor.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java, src/main/resources/english.yml, src/main/resources/plugin.yml
Adds beacon markers for players while they are in a siege zone. A beacon can have 4 different colors:
* White: Neither side has banner control.
* Red: The side that isn't the player's has control.
* Green: The player or their side has control.
* Yellow: The player has an ongoing banner control session.
____
Adds `WAR_SIEGE_BEACONS_ENABLED`:
* war.siege.switches.beacons_enabled
* Default: true
* If enabled, client-side beacons will be shown for players while they are in a siege zone.
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my …
=> Add beacon markers for sieges

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- With current code, casual players are limited in involvement with quiet sieges, because if they gain banner control, the minute they log off, it is gone.
- For example, in a 15 minute play session, they would spend 10 mins getting banner control, then 5 minutes getting points (very little), then the control would be lost when they log out.
- Thus it is generally pointless for such players to get involved in quiet sieges
- This PR addresses the issue by removing BC culling (something made possible by the recent battle session refactor)
- Thus a casual player can make a decent contribution at a quiet siege ...  but not an overwhelming one because bc is wiped when the battle session ends.
- This will also have the knock-on effect of 'activating' otherwise quiet sieges more regularly, and …
=> Remove BC Culling

src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
- With current code, sieges on the dynmap, once activated by a banner control session, keep the active icon even if the session fails (in the context that there is no other activity at the siege such as battle points or banner control).
- This gives the misleading impression to dynmap users that there is activity at the siege.
- In this PR I fix the issue by restoring the peaceful icon if banner control has failed.   
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and …
=> Pacify Inactive Sieges on Dynmap

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- After recent updates, 10 minutes for a BC sessions seems too long, but also 5 mins is too short (especially with the banner control reversal bonus
- In this PR, therefore I adjust the default to 7
____
N/A
____
N/A
____
=> Adjusted default config

src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java
- With current code, peaceful towns cannot be plundered
- This is not meant to be the case (and indeed the required error msg lang strings are missing)
- Peaceful towns are supposed to be immune to attack,  but if they get attacked before their go peaceful, and then go peaceful during the siege, then this should be "too late" to get protection from plunder.
- In this PR I fix the bug
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the …
=> Fixed bug where peaceful towns could not be plundered

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- With current code, the town screen xyz banner location text is almost redundant .......... because you can usually use the dynmap to get the approximate position of the banner, and then when you get close, you see the nice new beacon.
- In this PR I put the town screen xyz banner location text on a config (default disabled)
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/maste …
=> Put banner xyz on a config

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
- With current code, peaceful ruins can transfer between nations.
- This is not expected, and can also lead to problematic gameplay issues if such a ruin becomes the capital of a nation.
- In this PR I fix the issue by ensuring that peaceful ruins do not move (they will now stay nationless unless reclaimed)
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) …
=> Fix Peaceful Ruins Transferring

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- With current code, when a battle session ends, players who were in bc sessions continue to glow.
- In this PR I fix the bug, and remove the glow.
____
N/A
____
N/A
____
=> Remove glow when battle session ends

src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/resources/plugin.yml
- With current code, the terminology of some townyperms does not match the ingame texts and the user guide.
- Specifically, admins are asked to add  `*.siege.points` perms,  which are no longer appropriate, because as of the 0.2.2 scoring rework, those perms provide "battle points", which are later applied by battle winner into the single value of "siege balance".
- With 0.3.0 upcoming where people will be paying particular attention to the update guide, its likely best to do this now to save ourselves from unnecessary support work in the long term due to confusion arising etc.
- In this PR I fix the townyperms terminology to be accurate to the ingame texts & user guide.
____
N/A
____
N/A
____
By making this pull request, I …
=> Updated perms terminology to match ingame texts & user guide

src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/plugin.yml
- With last PR, although functionally there were no issues, I inadvertently messed up the perm nodes scheme.
- For example, kings with `towny.nation.siege.*`  would only expect to get nodes starting with `towny.nation.siege` i.e.
> towny.nation.siege.A
> towny.nation.siege.B
> towny.nation.siege.C
- They would not expect to get
> towny.nation.battle.X
- In this PR I fix the issue by the putting battle points into the correct node structure i.e.
> towny.nation.siege.battle.points
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Fix to perm nodes scheme

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/resources/english.yml, src/main/resources/french.yml
- With current code the presentation of the siege balance looks different from different sources, when the value is positive e.g.
- dynmap:     520
- hud:            520
- town screen: +520
- These presentation should all look the same.
- I prefer the dynmap and hud version, because: 
- The siege balance, being most important, should look most like a normal integer (i.e. no plus if positive).
- Also the lack of positive sign helps distinguish it from the battle points  presentations (which all have the plus sign)
- In this PR I fix the the issue by setting the siege balance to present like a normal integer, and like the dynmap and hud.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to …
=> Fix town screen presentation of siege balance

pom.xml, src/main/java/com/gmail/goosius/siegewar/objects/BannerControlSession.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- Today on EarthPol, players are very tough to kill
- This is allowing players to steal banner control by essentially running around the timed point zone for 15 minutes, sometimes giving them significant points when they steal control (due to the Reversal Bonus).
- Although other servers might not make players quite so tough, this issue may come up elsewhere too, possibly because reversals are more common than expected anyway, and possibly because the default session duration has been reduced from 10 mins to 7 mins. 
- In the PR I fix the issue by pausing the success of BC sessions if there are any enemy soldiers in the timed point zone.
- Thus a team which wants to gain or steal banner control no longer has an option of simply walking, dancing, or indeed, flying (and we heard a report …
=> Banner Control Session Pausing

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- With current code, battle points are sometimes referred to as "Battle Points" and sometimes as "Battle Score".
- "Battle Score" is essentially a dev artefact, does not appear in any documentation, and makes the display needlessly complicated, as "battle points" serve adequately in all cases to show the relevant points.
- In this PR I fix the issue - replacing all instances of "battle score" with "battle points". 
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify …
=> Remove "Battle Score" terminology

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSafeModeListener.java, src/main/java/com/gmail/goosius/siegewar/settings/Settings.java, src/main/java/com/gmail/goosius/siegewar/settings/Translation.java
- This code was mostly by Llama.
- I just added the short tick message, blocked commands, and increased robustness.
- This PR adds a safe mode for SiegeWar, in which the following are blocked:
- claiming
- block placing
- block destroying
- towns leaving nation
- sw commands
- swa commands
- Also there is a message on each short tick (e.g. to reach people who are just standing waiting for a BC session to start or siege to end etc.). 
____
N/A
____
N/A
____ …
=> Add SiegeWar safe mode

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSafeModeListener.java
Also reduces the shorttick message to only siegewar admins.
Not tested yet but should be ok.
____
____
Closes #177 
____
=> Move safe mode errors to the action bar.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- "Trap-Warfare" is the tactic of fighting battles by digging huge pits/traps (sometimes right under the siege banner), and trying to get enemy soldiers to fall into them to immediately kill or injure them.
- The tactic is generally hated by most players, who would prefer more face to face (or even arrow to face) combat when the action starts.
- This PR resolves the issue by blocking siege participants from altering any terrain in the timed-point-zone which is below the altitude of the siege-banner.
- Thus occasional fun trapping can be done in the wider siegezone area, but this mitigation should greatly reduce the tactic as an influence in in battles.
- Note: This mitigation feature, when enabled, also includes the requirement that players cannot get BC if below the banner altitude …
=> Trap-Warfare Mitigation

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
- With current code, explosions sometimes seem to bypass trap mitigation.
- I had tested this before and it seemed ok, so its possible this is an intermittent issues caused by siegewar having 2 listener methods for the same event.
- In this PR I fix the issue by combining all the required checks into just 1 listener method.
- *Note*: This issue is probably not urgent to hotfix or anything, because there is an easy option to ban TNT in siegezones, which most servers are probably already doing anyway. The ones mainly affected will be those with the optional cannons integration, but this integration is likely not widespread yet seeing as it was only fully released today with 0.3.0.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and …
=> Fix bug with explosions bypassing trap mitigation

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
This PR fixes a few of the remaining ways there were to break siege banners, and if a banner is broken, it will get replaced by a new one if the death firework effect is enabled (to prevent error spam in console when a player dies).
____
____
____
=> Patch remaining methods to break siege banners

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
`event.setBlockList(finalExplodeList);` was contained within the `if` statement that handles explosions for the Cannons integration, so `TownyExplodingBlocksEvent` would not be modified if trap mitigation was enabled but the Cannons integration was disabled. 
____
____
____
=> Fix trap mitigation explosion handling if the Cannons integration is disabled

src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- Today on a public server (not mine) I noticed that a battle session seemed to end in a messy way
- After the session should have ended, the siege side was listed as defender, and points kept being gained.
- But the next session was scheduled
- I investigated and am not sure precisely what happened
- However I did notice a general lack of defensive code around ending battles
- For example, the banner control code has much better defensive code
- In this PR I add more defensive control about battle sessions:
- Now it is impossible to get points in the session has ended
- Now there is a a try-catch around the complex part of the end-battles code
____
N/A
____
N/A
____
-  The changes are more trivial than what git shows. In …
=> Add Battle Sessions defensive code

src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- Fixed issue where towns might use peacefulness switching to escape occupation - fixed by recording the pre-peaceful occupier and returning them to it if they switch back to non-peaceful.
- Fix for battle session not started yet error message not showing (previous pr prevented this)
- Improved timed attacker win message
- Bug fix for merge issue (siege.getName() compilation problem)
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/ …
=> Misc small fixes and improvements

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
- With current code (possibly in 0.3.0), there is an exception when placing a chest in wilderness
- This small PR fixes the issue
____
N/A
____
N/A
____
=> Fix for index out of bounds exception

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- With current code, during the 10 minute battle session break, all players gets spammed with a warning every 20 seconds.
____
N/A
____
N/A
____
=> message spam fix

pom.xml, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/resources/plugin.yml
- With current code, `/sw nation ... ` commands only work for admins (not kings)
- This PR fixes the issue:
- In SiegeWarCommand class, I update the logic to allow nation commands to skip a  perms check which does not relate to them (and was causing the fail).
- In plugin.yml, I added a node for the new `/sw nation release`  inside the generic nation command node
____
- Added a node for `sw release` to the plugin yml so that kings can run it
____
N/A
____ …
=> Fixes to perms issues

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarAllegianceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
- With current code, soldiers who are not in the defending town are not counted as the defender.
- This PR fixes the bug, along with a less serious messaging bug
____
N/A
____
N/A
____
=> Allegiance logic fix

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
2 Fixes:
- 1.
- In the move to 0.3.1, it looks like guardian towns accidentally lost the ability to operate if they are occupied.
- The ability is important, because it allows a conquering nation to, naturally, pull in peaceful towns if it captures their guardian town.
- This PR fixes the issue.
- 2.
- An issue existed even back in 0.3.0 where a guardian town, once captured, could toggle off its "open" status, which would deny its guarded peaceful towns to the occupying nation
- The open requirement is no longer needed, as there is now no downside which needs optional avoidance by the occupier, in terms of occupied towns getting into its nation chat.
- This PR fixes the issues by removing the 'open town' requirement
____
N/A
____
N/A
____
- [N/A] I have tested this pull request for …
=> Guardian Town Fixes

src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
- With current code, nations have poor control over which peaceful towns they "peacefully occupy"
- As of 0.3.1, this is no longer a problem of foreign towns entering the nation chat, but there is a problem, because "occupation", in both its effects and interpretation, can unnecessarily create tension between two otherwise friendly neighbouring nations, neither of which would generally like to occupy peaceful towns belonging to the other nation.
- In this PR, I fix the issue, by disqualifying guardian towns UNLESS the prevailing nation of the guardian town IS the home nation of the peaceful town OR its enemy.
- Thus, now nation's who are not enemies will not come to occupy each other's peaceful towns.
____
N/A
____
N/A
____
- [N/A] I have tested this pull request for defects on a server. …
=> Add feature to allow nations to choose which peaceful towns to occupy

src/main/resources/english.yml, src/main/resources/french.yml
- With current code the "town captured/lost" terminology of the nation stats/war-history needs an update
- Towns are no longer captured/lost (as of the user-guide anyway). Rather "invaded" then "occupied".
- This PR updates the terminology
- No functional changes
____
N/A
____
N/A
____
=> Synch terminology of nation war history with user-guide

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- With current code there is a warning in the siegewar config relating to the Cannons plugin
- This warning is now redundant, as the Cannons team have fixed the problem
- In this PR, I remove the warning.
____
N/A
____
N/A
____
=> Remove redundant warning from config

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
- When town goes to ruin, just like its home nation is removed, the occupier nation should also be removed.
____
N/A
____
N/A
____
=> Remove occupation when town goes to ruin

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
- In the home defence feature, there was a small oversight, in that the home defence effects cause PVP to be forced ON in peaceful towns. 
- This is not a bug as such (after all, these towns are still immune to attack), however it is not in keeping with the general vibe of the peaceful towns feature.
- This PR resolves the issue by disabling home-defence-PVP-forcing for peaceful towns
____
N/A
____
N/A
____
- [N/A I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the …
=> Disable PVP-forcing for peaceful towns

src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java
- The following small issue has existing since the start of the system:
- If a nation town successfully defends a siege, the town gets the warchest.
- However this is not quite right, because statistically is very much the nation (& allies) who have done most of the fighting, not the town.
- This issue has become more exposed recently with the new text attributions of nation as defender, and the new emphasis on nation defences as a team effort.
- This very small PR resolves the issue by giving the warchest to the nation after a nation wins a siege defence.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I …
=> Improve warchest distribution

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
- With current code I think the home defence restrictions are too harsh
- The main purpose of these restrictions is to discourage exploits i.e. a nation arranging a fake-siege on one of its own towns to give the whole nation siege-immunity.
- As long as the restrictions are harsh enough to discourage exploits, they probably don't need to be much harsher.
- Practically, if they are too harsh, there will be player backlash, and server's will disable the entire feature.
- Current restrictions are:
- Nation cannot add towns
- PVP on in all nation towns
- No claiming/unclaiming by nation towns
- No recruiting by nation towns
- No spawning to nation towns except by residents
- With this PR I resolve the issue by removing the spawning block.
- I believe the other restrictions are still …
=> Remove home defence restriction on spawning

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/resources/english.yml, src/main/resources/french.yml
- For some time peaceful towns have been using the exploit of moving their homeblock to control their nation choice by placing the homeblock far away from an enemy guardian town, or near to a friendly one.
- Due to the long range of guardian town influence, it tends to be used more by towns towards the edge of a guardian's town's influence rage, still it is an unsavoury trick and exploit.
- This PR fixes the issue by preventing homeblock move for peaceful towns
- Peaceful towns can still do it if they wish, just have to toggle off peaceful, move the homeblock, then toggle peaceful back on again.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in …
=> Stop peaceful towns using homeblock-move exploit

pom.xml, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Closes #233 by removing the sieged restriction from guardian towns.
____
N/A
____
N/A
____
=> Remove sieged restriction for guardian towns

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/resources/english.yml, src/main/resources/french.yml
Closes #232 , by restricting homeblock move for sieged & occupied towns.
____
N/A
____
N/A
____
=> Restrict homeblock move for sieged & occupied towns

src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
- With current code, the appearance of revolt sieges by nation towns doesn't look right
- Specifically, the attacker is shown as the town e.g.     "Nice v.s. France"
- But this presentation is not in synch with the other siege types, and is less helpful
- What we really want to see is the name of the attacking nation e.g.  "Ostrogoths v.s. France"
- This PR resolves the issue by ensuring that for revolting nation towns, the nation is presented as the attacker.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced …
=> Revolt Siege Attacker Name Fix

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Closes #231 , by increases the attack/warchest cost whenever a nation hometown is attacked, with the increase becoming larger as the nation increases in size.
____
N/A
____
N/A
____
=> Add mitigation for annoyance sieges

src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
- Closes #237 , by ensuring that for historical sieges, the displayed nations do not change, even if the sieged town changes nation.
____
N/A
____
N/A
____
=> Fixed bug with display of historical nation participants

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
Closes #242 , by ensure PVP goes off in the remaining towns when a besieged town leaves a nation.
____
N/A
____
____
=> Fix nation towns not getting pvp off when besieged town leaves

src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java
- Small update to ensure the new metadata is torn down when siege ends
____
N/A
____
N/A
____
=> Added metadata teardown for primarytowngovernments

pom.xml, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
- With current code, there is a bug where, if an attacker abandons early, it later turns into a defender surrender
- (Which is pretty bad)
- The PR fixes this issue, and updates pom so the fix can be released as 0.3.9
____
N/A
____
N/A
____
- [NA] I have tested this pull request for defects on a server. 
=> Hotfix - Attacker pending abandon fix

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
Adds the ability to count the losing side's points against the winner of
a battle session. Configs will default to using the existing system,
when new setting is false the points will be more evenly applied.
calcPointsForBattleSession(Siege siege) added to
SiegeWarBattleSessionUtil.
Displays new language string on the /town screen showing what the
current BS winner will take away as points.
____
New Config Option: war.siege.scoring.winner_takes_all_points
- Default: true
- When true, at the end of a successful battle session all points go
to the winner of the session.
- When false, the losing side's points are deducted from the winners
side, making the losing side's efforts during the session matter, and
winners gain points slower.
____
Closes #257.
____
By making this pull request, I …
=> Option to Disable Winner-Takes-All BattleSession Scoring.

pom.xml, src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
- This PR adds a SiegeEnd event
- The event is called when the siege ends
- This Closes #287 
- This also adds the event required by [TownyHistories ticket 1](https://github.com/TownyAdvanced/TownyHistories/issues/1)
____
N/A
____
Closes #287
____
=> Sw 287 - Add SiegeEnd event

src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
- Adds some missing support for no-economy
- From town screen
- From dynmap
- From hud
- Note that in the PR, due to the relative complexity of supporting multiple row arrangements, 
and because of the urgency of this ticket,   
and because my chicken with cashew nuts is nearly here,
we don't completely remove the warchest row,
but rather just set it to show "-"
____
N/A
____
Closes #298 
____ …
=> SW-298 Added missing support for no-economy

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Fresh SiegeWar builds in 1.17+ do not have axolotl buckets accounted for by default, which allows users to place water (and a cute little axolotl) in the middle of a war siege zone. 
This simply just adds "axolotl_bucket" to default WAR_SIEGE_ZONE_BUCKET_EMPTYING_RESTRICTIONS_MATERIALS
____
Adds "axolotl_bucket" to default WAR_SIEGE_ZONE_BUCKET_EMPTYING_RESTRICTIONS_MATERIALS
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) for …
=> Adds "axolotl_bucket" as default option in config.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- Players can melt ice in siegezone to get water, which is not popular in siegezones on most servers.
- This PR adds ice to the default siegezone forbidden block list.
____
N/A
____
N/A
____
=> Add ice to blocks list

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/resources/english.yml, src/main/resources/french.yml
- Added `/swa revoltimmunity` command, which is used for setting revolt immunity on towns
- Renamed swa-set-siege-immunity command from `/swa immunity` to `/swa siegeimmunity`
- Added some commands which were missing from the generic /swa help list
____
N/A
____
Closes #314 
____
=> Sw 314 Added "/swa revoltimmunity" command

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- Optimized BC-Session Glowing: Now players in BC sessions only glow when enemies are in the timed point zone also.
- Added an action bar message to tell players how long they have left in their BC sessions.
____
- `banner_control.capturing_message_color='yellow'` - Determines the colour of the action bar message
____
Closes #260 
____
=> SW 260 - Optimized BC-Session-Glowing

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDynmapUtil.java
Small PR to add ruined towns to the automatic dynmap hide mode
____
N/A
____
Closes #327
____
=> SW-327 Added ruined towns to automatic dynmap hide

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/resources/plugin.yml
- Assigns permission nodes to existing and new ranks needed for SW.
- Also adds missing SIEGEWAR_COMMAND_SIEGEWARADMIN_NATION to
SiegeWarPermissionNodes enum.
- TODO: Fill in url to remaining nodes on command success.
____
____
____
=> Adds /swa installperms

src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
- Currently players keep level if killed on death during battles (which is good).
- However they also drop some XP which can be taken the pplayer who killed them.
- This allows two collaborating players to (rather noisily) farm XP, by repeatedly killing each other, losing no XP, but continuing to gain XP.
- In this PR I fix the exploit by ensuring that players killed in battle drop no XP.
____
N/A
____
Closes #353 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution …
=> SW-353 Fix to prevent XP farming

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
When nationzones are enabled, sieges can be started but the banner used to start one is removed by Towny. 
This PR changes the logic of the evaluatePlaceStandingBanner method, turning it into a boolean, which returns true when a banner is successfully placed to start a siege. All other scenarios either return false or end up throwing an exception which doesn't result in the TownyBuildEvent being un-cancelled.
____
____
Closes #397
____ …
=> Fix banner not being placed inside of NationZones upon Siege start.

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
Citizens NPCs throw PlayerTeleportEvents, which SiegeWar was picking up on, this PR ignores their teleport events.
____
____
____
=> Fix Citizens NPCs being teleported to spawn.

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarAllegianceUtil.java
Solves for siegesickness being given to the defending town's mayors,
assistants and guard, when that town doesn't have a nation.
They were only being tested for the nation battle points node.
____
____
Closes #408.
____
=> Fix Liberation siege incorrectly choosing SiegeSide for Siege

pom.xml, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
Displays the BattleSession, BannerCap times left as text and progressbars using Minecraft's BossBars via the Adventure API shaded in Towny.
____
/sw preferences bossbars on/off - Allows a player to turn off the bossbars.
____
Closes #407
Closes #334
____
=> Add BossBar progressbars for BattleSessions & Banner Cap timers.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
Good for keeping players from being underneath the banner in pre-dug-out caves.
____
New Config Options:
- war.siege.distances.banner_control_vertical_distance_blocks_up",
- 16
- This is the vertical distance a soldier must be within above the
Banner.
- Note that the horizontal distance is always the same as the Towny
townblock size.
- war.siege.distances.banner_control_vertical_distance_blocks_down",
- 4
- This is the vertical distance a soldier must be within below the
Banner.
- Note that the horizontal distance is always the same as the Towny
townblock size.
Removed Config Option:
war.siege.distances.banner_control_vertical_distance_blocks
____
Closes #405.
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and …
=> Split vertical distance requirements surrounding capping into separate up and down values.

src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
=> Force a correct Locale when converting explosion list to uppercase

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarNationAddonCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/resources/english.yml, src/main/resources/french.yml
- SiegeWar now uses the StatusScreen objects to add details to Towny
status screens.
- Includes:
- Nation Refund, Plunder, Military Salary details are now
click-to-collect from the Resident Status Screen.
- Town status screen moves many Siege details to [Sieged] hoverable
component.
- Nation status screen only shows lists when they are greater than
zero.
- Made /n screens show only 10 occupied towns per list, with the option to
click the screen to run the above commands and see the full lists.
____
/nation siegewar occupiedhometowns {nationname}
/nation siegewar occupiedforeigntowns {nationname}
Shows full lists of occupied towns.
____
Closes #413
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that …
=> Use Towny's new StatusScreen components.

pom.xml
In https://jitpack.io/com/github/TownyAdvanced/SiegeWar/0.7.0/build.log a Build Failure occurs because of 
`Failed to execute goal on project SiegeWar: Could not resolve dependencies for project com.gmail.goosius:SiegeWar:jar:0.7.0: Could not find artifact net.citizensnpcs:citizensapi:jar:2.0.28-SNAPSHOT in spigot-repo `
Adding this to the pom allows for it to build properly and allows jitpack to build each version so we can utilize it in our repos without errors. …
=> Add Citizens-Repo because it fails to build without it. (tested in 0.7.0)

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java, src/main/resources/english.yml, src/main/resources/french.yml
- With current code, if a server shuts down while a battle is in progress, all battle points are lost.
- This PR addresses the issue as follows:
- Battle points now persist to the DB whenever they are gained. 
- If the server shuts down during a battle session, then on the restart of the plugin, the plugin immediately resolves all battles as a "draw", applying both attacker & defender battle points to the siege balance.
- If this occurs, a message is shown in the console during server restart.
____
N/A
____
Closes #264 
____ …
=> Persistent Battle Points

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
... again.
I have not tested this, but you can see that when the battlesession ends we tell the players' bossbars to update.
____
____
____
=> Fix empty battle session boss bar being displayed to players

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- With current code, the battle session scheduler config requires UTC times to be specified. This is not convenient.
- This PR improves the config, by allowing LOCAL times to be specified (i.e. using the timezone at the server location).
- This PR also changes the default configured battles times to 1/hour, which is a more sensible default than the current one.
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) for …
=> Change Battle Session Scheduler config to use LOCAL instead of UTC times

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
- As discussed in the ticket, this PR improves chest placement so that players will get the "too many facing chunks" error less often.
- Now they will only get it if the chunk faces two different besieged towns.
____
N/A
____
Closes #455 
____
=> Chest Placement Improvement

src/main/resources/english.yml, src/main/resources/french.yml
- There is a bug that the message does not display the values correctly.
- This is because the lang string does not have the required parameters
- The PR fixes the issue
____
N/A
____
N/A
____
- [ N/A I carefully checked the code; it should be fine ] I have tested this pull request for defects on a server. 
=> Fix for banner-control-session start message

src/main/java/com/gmail/goosius/siegewar/playeractions/StartLiberationSiege.java, src/main/resources/english.yml, src/main/resources/french.yml
- Wall breaching has an unexpectedly nasty implication at liberation sieges: Because the town owner doesn't get to choose the liberator who will generate breach points, an unpleasant liberator could grief the town excessively, by racking up breach points and letting the occupier team (who is also hostile to the town) do a lot of damage.
- In this PR I fix the problem as follows:
- Liberation sieges at nation towns now require that the liberator and natural nation be allies.
- Liberation sieges at nationless towns can proceed as before.
- The Liberator will be the one who can rack up breach points.
- It is possible that the Liberator is careless or unpleasant.
- However the town has multiple options to solve this: In the short term it can surrender, and in the medium term it has the simple …
=> Fix for wall breaching in liberation sieges

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- With current code there is a needlessly confusing bit of display logic, which arranges the town screen differently in different scenarios
- This is unnecessary, and doesn't work anymore with Wall Breaching, as those points might be missing.
- In the PR I remove the redundant logic.
____
N/A
____
N/A
____
=> Removed redundant display logic

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- As per #462 , a siege balance cap may be a useful option for servers, to even the balance between large and small nations
- This PR adds it.
____
```
siege_balance_cap:
value: '20000'
```
____
Closes #462 
____
=> Siege Balance Cap

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
Fixes placement in nationzone issue
____
NA
____
NA
____
- Tested fix in world-protected wilderness
- Could place banner and start siege as in 0.7.6
- Although I didn't test a nationzone as such, I'm confident this fix will work, as the code which allows placing in siegezones has not changed and can be expected to kick in immediately after the siege start (see method "onNationZoneStatus")
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) for …
=> nationzone fix

pom.xml, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/resources/english.yml, src/main/resources/french.yml
- Currently the install guide requires manual file changing to set up the Towny configs which are recommended for SW
- To make life easier for installers, the PR replacing the existing `swa installperms` command with `/sw install`, which sets up both the required/recommended configs and perms.
__
- New command: `/swa install`
____
Closes #474 
____
=> Install command

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/Settings.java, src/main/java/com/gmail/goosius/siegewar/utils/MigrationUtil.java
- Since 0.7.0, there are now 18 config field which need migration.
- This PR automates that task, by doing it automatically when, after dropping in the new jar, the server is restarted.
____
N/A
____
N/A
____
=> Automatic config field migration

src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsListener.java, src/main/resources/english.yml, src/main/resources/french.yml
- With current code, cannons can be fired, without reply, from towns which are not the sieged town
- This does not seem good
- In this PR I fix the issue by forcing siegezone cannons to be fired from either the besieged town or the wilderness
____
N/A
____
N/A
____
(I viewed the previous PR on cannons refactor and confirmed that the cannons method used here is correct) …
=> Cannons Integration - added new rule to improve gameplay

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- Most server users today don't seem hardcore enough to remove players from the dynmap for the sake of enabling extra military tactics.
- This PR leaves the map-hiding feature as-is,  but simply sets a more sensible default of enabled=false.
____
N/A
____
N/A
____
- [  N/A  ] I have tested this pull request for defects on a server. 
=> Changed map hiding config default to false

src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- Currently, at the end of a battle session or siege, the banner cap boss bars do not get removed.
- This PR fixes the issue by removing them in those scenarios
____
N/A
____
N/A
____
- [  N/A  ] I have tested this pull request for defects on a server. 
=> Fxed banner cap boss bars not disappearing

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
- Currently SiegeWar cannot work with the (apparently popular) PvpToggle plugin, because that plugin allows players to go immune to damage in Siegezones. 
- This PR resolves the issue, by overriding the damage cancelling that pvptoggle is doing.
- Servers will still have to config the pvpt messages to blank to avoid getting false positive cancellation spam. After that, the integration should be fine.
- Server owner Tree has requested this.
____
Na
____
Na
____
- [ Na - I have limited capability to test pvp locally. Double checked code and I think it is ok.
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the …
=> Deal with pvp toggle

src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarWallBreachUtil.java, src/main/resources/lang/en-US.yml, src/main/resources/lang/fr-FR.yml
- With current code, a town hostile side has to cap the banner to get the WB bonus
- This is to stop them logging off/on at homeblock to get ez bonus
- This is messy, bcs first they probably need defender to cap (to breach walls), then get in, secure path, then cap, then go to homeblock.
- I have come up with a better way to patch exploit (will follow in a separate pr)
- In this pr I remove the remove the banner cap requirement for bonus
____
na
____
na
____
- [ x ] I have tested this pull request for defects on a server.  …
=> Wall Breaching - Remove banner cap requirement for bonus

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/lang/en-US.yml, src/main/resources/lang/fr-FR.yml
As described in #501 , the current feature of the Capping Limiter has a key problem:
- It does not actually stop players from attending sieges once they hit their limit.
- Thus player's don't truly get any break, and may feel the need to log overtime to counter an opponent who is logging overtime.
- This PR solves the issue: 
- Feature renamed. Capping Limiter -> Siege Attendance Limiter
- Players can no longer attend sieges once they hit their limit (due to war sickness)
- Attendance is marked if a player caps, damages, or is damages by another player at a Siege.
- Weekend/Weekday limits are increased by +1
---
- An essential Health & Safety feature.
- Without this feature, Sieges can often become races to see who can spend the most time online.
- This has a bad effect on player health & …
=> Refactor: Capping Limiter -> Siege Attendance Limiter

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- The battle session scheduler method (not to be confused with the feature) sometimes starts too soon.
- In particular if an admin force-ends the session in the same minute as it is due, it will start immediately.
____
N/A
____
N/A
____
- [ N/A very small fix should be fine ] I have tested this pull request for defects on a server. 
=> Scheduler method fix

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- This feature by Ceedric is pretty much standard now, so this is overdue.
- Also with the upcoming changes to keep inv, this feature becomes critical to keeping non-participants from interfering.
- Given the criticality, I updated the name slightly to that it will auto-enable on all servers (of course they can later configure it off)
- I also updated the warning time to a more reasonable default of 20 seconds.
____
N/A
____
N/A
____
- 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify …
=> Enable non-participant punish feature by default

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
- Currently attendance limiter only culls old sessions from a player if that player online when a session starts
- Not good
- This PR fixes the issue (very small code change)
____
N/A
____
N/A
____
- [  N/A ] I have tested this pull request for defects on a server. 
=> fix for attendance limiter culling

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattlefieldObserverUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
- With recent code, a few methods have been added which check for siegezone proximity on each PVP hit
- I think this could potentially be causing issues vis. lag, especially in big fights
- This PR should fix the issue, by using cached siegezone proximity checking in the following methods:
- 4 battlefield observer related methods
- 1 listener method for undoing PVP cancellation by Townyfriendly fire 
- 1 listener method mainly for undoing PVP cancellation by all other plugins
- 1 method for warning players about being in a siegezone
- Also I improved performance (but did not actually add caching) in the following listener methods
- Townblock PVP event check
____
N/A
____
N/A
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my …
=> Add Siegezone Proximity Caching

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- With current code some pvp un-protection features are not configged
- This PR adds the configs
____
```
PVP_PROTECTION_OVERRIDES(
"pvp_protection_overrides",
"",
"",
"",
"############################################################",
"# +------------------------------------------------------+ #",
"# |               PVP Protection Overrides               | #",
"# +------------------------------------------------------+ #",
"#                                                          #",
"# Other plugins, including Towny, can protect players      #",
"# from PVP, even when those players are in Siege-Zones.    #",
"# 						            #",
"# This section allows server owners to override those      #",
"# protections, and stop them from working in Siege-Zones.  #", …
```
=> Pvp unprotection configs

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- This PR switches changes a default value to a more sensible one
- (Players seem generally to expect winner take all to false)
____
N/A
____
N/A
____
=> Set winner takes all to be false by default

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
- On servers with combat tag, with current code, if a player logs out in a SZ they get double death points
- First combat tag kills them, then SW awards points
- Then SW kills them again (lol), giving a second SW points award
____
N/A
____
N/A
____
=> Fixed double death points when logging out

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/resources/lang/en-US.yml
Closes #535 
Closes #534 .... don't know if this was fixed before this PR. But with this PR it is confirmed by testing as not an issue.
____
```
TRAP_WARFARE_MITIGATION(
"trap_warfare_mitigation",
"",
"",
"",
"############################################################",
"# +------------------------------------------------------+ #",
"# |               TRAP WARFARE MITIGATION                | #",
"# +------------------------------------------------------+ #",
"############################################################",
""),
TRAP_WARFARE_MITIGATION_ENABLED(
"trap_warfare_mitigation.enabled",
"true",
"",
"# If this setting is true, then players cannot build/destroy blocks in the Siege-Zone below the siege banner altitude.",
"# Also banner control cannot be gained if the player is below …
```
=> Added Cap-Zone option to trap mitigation

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
- With current code, if trap mitigation is on, there is a weird effect where just below banner you cannot do block interactions, but a few blocks lower down, you can
- This PR tweaks it so that the protect radius is 16 block horizontally, including all verticals
____
```
TRAP_WARFARE_MITIGATION_NEAR_BANNER_ONLY(
"trap_warfare_mitigation.near_banner_only",
"true",
"",
"# If this setting is true, then the restrictions apply only to a 16 block horizontal radius around the Siege-Banner.");
```
____
N/A
____
- [ x ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Trap mitigation tweak

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
- Current the HUD tab-prompt shows all sieges, including inactive ones.
- This is only marginally useful, and mostly just confusing.
- This PR resolves the issue, by showing only active sieges on the HUD tab-prompt
____
N/A
____
Closes #547 
____
- [ N/A  ] I have tested this pull request for defects on a server. 
=> Make HUD tab-prompt show only active sieges

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
- With current code artefact explosions do not damage the player who carries the artefacts
- This has something to do with the location being player.getEyeLocation() but I don't understand why
- This PR fixes the issue by setting location to simply player.getLocation()
____
N/A
____
N/A
____
- [ x ] I have tested this pull request for defects on a server. 
=> Fixed Artefact Explode not damaging holder

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
This was happening: https://pastebin.com/21ZtZdcV because instant_damage is not a valid PotionEffectType.
____
____
____
=> Fix arrow_of_doom from instant_damage to harm.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
- This PR causes the arrow-of-doom config fix to be automatically applied on deploy of 0.7.18
____
Na
____
Na
____
- [ na ] I have tested this pull request for defects on a server. 
=> Auto-apply the arrow of doom fix

src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Adds a test during Domination Awards loading, that skips over any awards that are:
- not custom_effect
- an invalid PotionEffectType
- an invalid EnchantmentType
____
____
____
=> Validate user-input from domination awards config to be sure it will load.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
A few default config changes for balance:
- Adjusted some weapon and potion effect levels
- Changed tools to diamond, because golden tools cannot successfully mine certain important materials.
____
Na
____
Na
____
- [ na ] I have tested this pull request for defects on a server. 
=> Artefact Balancing Updates

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSelfListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/resources/lang/en-US.yml
Battle Sessions don't need to run if there's no sieges to fight over.
____
New Config Option:
battle_session_scheduler.cancel_session_when_no_active_sieges
- Default: true
- Should sessions be cancelled when there are no active sieges?
____
Closes #619
____
=> Cancel battle sessions starting if there is no active sieges.

pom.xml, src/main/java/com/gmail/goosius/siegewar/TownOccupationController.java, src/main/java/com/gmail/goosius/siegewar/events/PreInvadeEvent.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
____
____
Closes #604 via a separate plugin.
____
=> Add PreInvadeEvent which can stop the invasion of a town after a successful siege.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/resources/lang/en-US.yml
When either the new capital or old capital are sieged, prevent that
king-change event.
____
New Config Option:
war.siege.switches.besieged_capitals_cannot_change_kings
- Default: false
- If this value is true, then a town which is a capital of a nation
that is under siege, cannot change capital to another city via /n set
king|capital.
____
Closes #641.
____
=> Add option to prevent sieged nations from changing their capital. (Configurable.)

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Expiry times had an added 5 in the multiplier used to calculate millis per day, leading to expiry days counting for about 10 days each.
____
____
____
=> Fix global domination expiry times being set incorrectly.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Some servers may want to prevent any nation capital city from becoming peaceful on the town-level.
____
New Config Option: neutral_towns.capitals_allowed_neutrality
- default: "true"
- If this is true, a nation capital can be a peaceful town. If false, any capital will not be able to turn peaceful.
____
____
=> Config Option: prevent capitals becoming peaceful.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/lang/en-US.yml
____
New Config Node:
war.siege.switches.unjail_residents_when_attackers_win_battle_session
- Default: false
- When true, if an attackers wins the battlesession against a sieged town, that town's jailed players that belong to the attacking nation will be freed from the town's jail.
____
Closes #701.
____
=> Jailbreaks triggered by attackers winning battle sessions.

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
Old message said no permission. Now it says they don't belong to a nation.
____
____
____
=> Improve error message when starting a siege without a nation.

pom.xml, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
____
New Config Option: war.siege.switches.enabled_glowing_on_players
- Default: true
- When true, players will have a glowing effect.
____
____
=> Make glowing for banner control sessions optional.

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/resources/lang/en-US.yml
- *WARNING* Not reviewable until PR 720 is merged
- Currently there is a bug where you need an active siege to do swa siege x setplundered/setinvaded
- This very small PR fixes the issue
____
N/A
____
N/A
____
- [NA too trivial] I have tested this pull request for defects on a server. 
=> Fix bug with swa setplundered/setinvaded

src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java
- *WARNING* Not reviewable until the PR 721 is merged
- Currently there is a bug where the warchest (of 0) is granted with message on a revolt siege win
- Remove this grant & message, because in revolt sieges, there is no warchest
____
N/A
____
N/A
____
- [NA too trivial] I have tested this pull request for defects on a server. 
=> Fix 0 balance warchest awarded message shown upon winning a revolt siege.

src/main/resources/lang/en-US.yml
- *WARNING* Not reviewable until the PR 723 is merged
- This small PR changes the terminology of "Invaded" to "Captured", as "Captured" feels like a more intuitive description given the recent simplification of the occuopation system.
____
N/A
____
N/A
____
- [N/A changes were too low risk] I have tested this pull request for defects on a server. 
```
****
=> Changed terminology - "Invaded" to "Captured"

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/lang/en-US.yml
- *WARNING* Not reviewable until the PR 732 is merged
- Given that Ceedric's non-official-participant war sickness is now de-rigeur, and that peaceful town residents cannot be official participants due to not having nation rank,  this means that any specific code for "peaceful town war sickness" is now effectively redundant and can be removed.
- This PR does this
- It also tweaks the rules around war sickness,  so that any unofficial-participant in a non-besieged town only gets special war sickness. This is expected to particularly help peaceful shop towns, to stop their customer's getting overly sick due to nearby sieges.
____
____
____
- [N/A low risk] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive …
=> War-sickness improvements

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/resources/lang/en-US.yml
- town.isAllowedToWar() is used for towny capture sites, and admin/spawn towns, to protect those towns.
- It makes sense that SiegeWar should respect those protections
- However there doesn't appear to be any scenario, where it makes sense to restrict players from those towns from starting sieges. Example: admins from admin towns will actually sometimes want to start test sieges.
- Thus this PR removes that start-siege restriction.
____
____
____ …
=> Remove restriction of prevening siege-starting by residents of towns with is !isAllowedToWar

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java, src/main/resources/global.yml, src/main/resources/lang/en-US.yml, src/main/resources/plugin.yml
- With current code, SW is hijacking/re-using the native towny town "neutral" flag to indicate peacefulness
- This is bad for 2 reasons:
- The Towny neutral flag comes with an extra daily monetary cost, which interferes with SiegeWar's system balance, because in SiegeWar, peaceful towns are already fully costed, via restrictions on their residents, vulnerability to instant capture, and occupation tax.
- This arrangement forces towny to support duplicate commands and message e.g. "/t toggle neutral", "/t toggle peaceful"
- In this PR, I put the peaceful town flag into SiegeWar metadata.
- SiegeWar system balance is restored.
- And Towny developers can now remove the duplicate commands and messages!.
____
____
____
- [ x  ] I have tested this pull request for defects on a server. 
By making …
=> Move peaceful town flag into SiegeWar metadata

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java
PR largely removes the usage of Translation, which defaults to the server default locale, replacing it with Translatable where possible.
Exceptions:
- EventListeners do not always deliver a player that will be shown the cancel message.
- Dynmap/Bossbar/SiegeType areas where we actually do want things to be using the server default locale, for universal messages without individual readers.
Additionally, many areas where we caught TownyExceptions we were not choosing to show the message in the player's locale.
Fixes a thing in the BannerControlUtil that would cause an evaluation to fail before completion.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in …
=> Translate our translatable messages more thoroughly.

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/utils/DataCleanupUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/PermissionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/PermsCleanupUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMilitaryRanksUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownOccupationUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java, src/main/resources/lang/en-US.yml
- For the new occupation system to work, occupied towns can no longer have use of military ranks.
- This PR fixes it so that both Peaceful & Occupied towns cannot get any military ranks
- On capture/peacefulness, all ranks are stripped
- Sheriff is no longer a military rank (migration util added to fix that)
____
____
____
=> Military ranks fix

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/objects/SiegeCamp.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderTimedWin.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarAllegianceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/lang/en-US.yml, src/main/resources/plugin.yml
- With current code, sometimes the town is the attacker (revolt), and sometimes the town is the defender (conquest)
- I think this is more complicated for users to understand, compared to the "attacker = nation, defender = town" logic which SW had in early versions.
- This is also a problem for siege balancing by server owners. Because typically a server might want to give a straight points advantage to the "town side", but this is not possible.
- This PR changes the logic to be simpler so that:
- Attacker = attacking nation
- Defender = defending town 
- As part of the above change, this PR makes some related changes to the perms in **plugin.yml**. However because the affected perms are not expected or required to be specified outside of plugin.yml,  I deem this low risk compared to the …
=> Simplify Attacker/Defender logic

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
- With current code, the peacefult-towns counter check and associated status messages .... occurs **before** the native Towny newday message, instead of **after** it, as would be expected.
- This seems needlessly confusing
- The only functional effect I can think of, is that in previous SW versions this would allow the towns to dodge the "Neutal Town Extra Upkeep" effect. However since SW no longer uses the "Neutral" town scheme, nor its associated extra upkeep cost, this effect no longer applies.
____
____
____
- [ NA too trivial ] I have tested this pull request for defects on a server. 
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, …
=> Move peaceful-towns counter check to after newday event, not before

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
- Moved nation refund to be trigger on /sw collect, instead of /sw nation claimrefund.
- This is simpler, plus it ensures that even if the former king is now townless, they can still claim without issue.
____
____
____
=> Moved nation refund to be trigger on /sw collect

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
- With current code, if a player is standing on a dirt block, apparently at the banner altitude, they will fail the banner control session, because a dirt block is actually very slightly under banner altitude.
- The PR adds a fix by adding a little leniency.
____
____
____
=> Banner Altitude Checker Fix

src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/resources/lang/en-US.yml
- Wth current code, in an active revolt siege, when a chest is placed by the town, a string missing error is shown.
- With current code, in an active resolve siege, when a coloured flag is placed by the town, the error message is not very informative e.g. "No permission".
- This PR fixes issue 1, and improves the messaging in issue 2
- The PR also improves the messaging around subvert when the player hasn't permissions
____
____
____ …
=> Fix invade/plunder/subvert block placement messaging

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/metadata/SiegeMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/utils/DataCleanupUtil.java
- With current code, sieges do not get migrate from the legacy to the new format (and indeed bad things happen if you load up with legacy sieges.
- When upgrading to SW2.0.0, Servers will be recommended to first let all current sieges be completed, including invade/plunder, so that players might have some time to study the new mechanics before sieges restart.
- This PR supports those servers who choose to go against recommendations and migrate while there are active or recently ended sieges. The migration is deliberately robust to carefully avoid any data corruption issues: Legacy conquest sieges are automatically kept, the rest are automatically deleted. 
- The PR also fixes a bug with occupation migration, where the natural nation was getting the town after migration.
- This PR also …
=> Siege migration

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarNationSetOccupationTaxAddonCommand.java, src/main/java/com/gmail/goosius/siegewar/metadata/NationMetaDataController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- With current code the default occupation tax is very small e.g. 2
- Small differences in this could be important e.g 2.5, 1.5
- Thus this PR turns the value into a decimal
____
____
____
=> Set occupation tax to be double

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/lang/en-US.yml
- This PR fixes the revolt siege start message to give the nation name.
- The messages for "abandon/surrender initiated" and "abandon/surrender confirmed" contained a lot of duplication. The PR removes the duplication.
- This PR changes the siege status names of "Pending X" to "X Pending" for consistency
____
____
____
=> Messaging improvements and fixes

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/resources/lang/en-US.yml
- Tidied up the nation screen, by putting the siegewar elements (except occupation tax), into their own hover boxes
____
____
____
=> Improved nation screen sw elements

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java, src/main/resources/lang/en-US.yml
- It has been accepted for a while that the current peaceful-town-capture system is too complicated
- This PR returns the system to something closer to the 0.1.0 version
____
```
PEACEFUL_TOWNS_GUARDIAN_TOWN_SEARCH_RADIUS(
"peaceful_towns.guardian_town_search_radius",
"1200",
"",
"# Given any peaceful town, the largest-by-townblock, non-peaceful, non-sieged town, in this radius around the homeblock, is considered to be the guardian town.",
"# If a nation owns the guardian town, that nation can instantly subvert & occupy the peaceful town"),
```
____
Closes #617 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that …
=> Revert "TownyInfluence" to "Guardian Towns"

src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
- With current code and default settings,  every siege ends at the same time .... after the last battle session of the week, thus severely spamming the console if there are many sieges.
- This PR resolves the issue by staggering the siege endings.  Now there will be at most one siege ending every 20 seconds.
____
____
____
=> Staggered siege endings

src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
- With current code, it is not possible for a revolt to break through siege immunity
- It also adds a minor optimization around upfront-siege-cost
- Also fixes a small messaging bug
____
____
____
=> Fixed revolt prevention bug

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/resources/lang/en-US.yml
- With current code, there is a problem with recording plunder lost:
- Unlike in the previous occupation system, when you capture a town, all traces of the previous owner are removed.
- Thus if a winning besieger invades first before plundering ... the system has no knowledge of the previous nation, to record the national plunderLost stat.
- This PR fixes the problem in the safest way possible, by simply removing the display of the plunderlost stat
- In future, perhaps in SW 2.1.0, this can be fixed, probably required adding to the siege object metadata scheme. Something which I am averse to doing in SW 2.0.0 as the feature is not critical, the fix is not trivial, and I'm already in the middle of regression testing.
- The fix could potentially be part of wider upgrade of the feature too - …
=> Fixed nation plunder stats

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
- With current code, revolt sieges started against a nation are counted in their "max attacks"
- This should not be the case. Only conquest sieges started by a nation should count
____
____
____
=> Fixed max attacks per nation

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/BattleSession.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/lang/en-US.yml
- For some time I've been impressed with how World-of-Warcraft handles warring player factions ..... i.e. the factions (horde, allience), cannot even speak to each other in-game.
- This feature naturally reduces toxicity, since a primary source of toxicity (enemies smack talking each other in battle) is completely removed.
- This PR adds a flavour of this to SiegeWar:
- In keeping with the SW2.0.0 ethos this feature is very simple:
- In SiegeZones, local chat is not possible
- During Battle Sessions, and for 10 mins after, global chat is not possible
- Notes:
- Naturally players may try to find a way around this. In particular, some may try to mouth-off on the server discord. However I expect this workaround will not be reduce much the impact of this feature, because:
- While fighting, …
=> Add Chat-Restriction feature to reduce toxicity

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarWarningsUtil.java, src/main/resources/lang/en-US.yml, src/main/resources/plugin.yml
- Background
- As per the theme of 2.1.0, this PR addresses toxicity.
- A leading cause of toxicity on some servers, is that the "stakes" of sieges are too high. 
- Example: If town is set to lose a big amount of plunder on a siege-loss (e.g. 80% of the town bank), then both the siege and its aftermath will tend to be high-stress/high-toxicity affairs.
- Alternatively if the town was set to lose a relatively low amount of plunder (e.g. 15% of the town bank), it would be hard to argue after the release of SW 2.0.0, that this wouldn't improve the atmosphere on the server, considering:
- The list of victor-benefits which do not change, including increased national reputation, expansion of the nation, reduction of an enemy nation, and taxing the occupied town.
- The list of victor-benefits …
=> Add 'Bad-Config Warning' for High/Low plunder

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/objects/BattleSession.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java, src/main/resources/lang/en-US.yml
- This PR adds a disabled for /tell while battle sessions are active
- It also bring all disables into the same simple scheme of "when a battle sessions is active, and for 10 mins after"
____
____
____
=> Disable /tell while battle session is active

pom.xml, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
- With current code, there is a bug in the PlayerDeath class, which fails to award points, and throws a nullpointer instead.
- Strangely, nobody has logged a bug ticket yet for this, even though it seems to have been present since SW 2.2.0, and seems to prevent any death points being awarded.
- This PR fixes the issue, and also does one refactor-rename of a method for clarity.
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the SiegeWar [License](https://github.com/TownyAdvanced/SiegeWar/blob/master/LICENSE.md) …
=> Bugfix for death points

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSafeModeListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSelfListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
- In the current code, in many cases, if an event has been cancelled by another plugin, SiegeWar ignores the cancellation.
- For example, if another plugin cancelled the death event.....SW would still process the death and award kill-points.
- This is not good, we want SW to respect the actions of other plugins where possible.
- This PR resolves the issue by adding the missing ignoreCancelled=true tags.
____
N/A
____
Closes #832
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my …
=> Add missing 'ignoreCancelled=true' tags

src/main/java/com/gmail/goosius/siegewar/SiegeWar.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/resources/lang/en-US.yml
- With current code there is an exception when trying to use the HUD with Folia
- As per the issue ticket, HUD's generally are not yet possible with Folia
- This PR adds logic to prevent HUD usage (with an error message) is folia is present
____
NA
____
Closes #857
____
- [NA too trivial] I have tested this pull request for defects on a server. 
=> Added logic to block HUD in folia

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java, src/main/resources/lang/en-US.yml
- With current code, the money warnings can get skewed by towns/nations containing lots of money, either from admins testing or from Players cheating.
- This PR helps to resolve those issues by:
- Discounting NPC towns
- Discounting towns with balances x3 or more times above the average
____
NA
____
Closes #874 
____
=> Improve Accuracy of Money Warnings

src/main/java/com/gmail/goosius/siegewar/SiegeController.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionEndedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionStartedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeCampStartEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSelfListener.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java, src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderTimedWin.java, src/main/java/com/gmail/goosius/siegewar/utils/DiscordWebhook.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/lang/en-US.yml
Users can now have siege war notifications in their discords
it uses the localization so works on all supported languages
____
DISCORD_WEBHOOK (comment)
DISCORD_WEBHOOK_ENABLED (boolean)
DISCORD_WEBHOOK_URL (string)
DISCORD_WEBHOOK_NOTICIATION_SESSION_START (boolean)
DISCORD_WEBHOOK_NOTIFICATION_SESSION_END (boolean)
DISCORD_WEBHOOK_NOTIFICATION_SIEGECAMP_START (boolean)
DISCORD_WEBHOOK_NOTIFICATION_SIEGE_START (boolean)
DISCORD_WEBHOOK_NOTIFICATION_SIEGE_END (boolean)
DISCORD_WEBHOOK_NOTIFICATION_SIEGE_REMOVE (boolean)
____
____ …
=> Discord webhook

src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java, src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java, src/main/java/com/gmail/goosius/siegewar/events/BannerControlSessionEndedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionEndedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/BattleSessionStartedEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeCampStartEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java, src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java, src/main/java/com/gmail/goosius/siegewar/objects/Siege.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/DiscordWebhook.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java, src/main/resources/lang/en-US.yml
- show help if args length is 0 (would throw exception before)
- fix besieged town name not getting sent to ingame translatable on siege remove 
- fix session end webhook notification
before if a session ended and it had battles there'd be an exception and no webhook notification but now it works
- return from send notification if not active
- strip formatting from event messages properly
- fix beacon exceptions on folia
- add BannerControlSessionEndedEvent
____
____
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the …
=> Fix messaging-related issues, webhooks, folia-related beacon exception, add BannerControlSessionEndedEvent

src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeCampUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleCommanderUtil.java
Rechecks that the nation does not have too many active Conquest sieges
when a SiegeAssembly finishes.
Removes unused 2 imports.
____
____
Closes https://github.com/TownyAdvanced/SiegeWar/issues/886.
____
=> Fix max-conquest-sieges-per nation being bypassed by Siege Assemblies.

src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
Sessions might not be starting an extended period of time, this PR makes it possible for the code to look more than 1 day in advance when it cannot otherwise find a next session for the day.
It will look up to 6 days away, since we don't want to look at the current day of the week.
____
____
____
=> Make it possible to show the time to the next BattleSession from more than 1 day in advance.

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Allows the operator of the server to configure the distance the banner can be captured at, following the same rules for the radius as before.
Does not change default behaviour, negative values will default to Town Block size and default is -1 - This does mean that it cannot be "disabled" - setting it to 0 is theoretically possible to capture (this can be tested by tp to banner location with .0 added to each coordinate) but likely impossible in reality.  - This could easily be rectified by changing "0" to use Town Block Radius, and negative values to disabling it entirely (or simply returning that they are not in the zone as it would be impossible) - Felt this was not relevant, the intention is not to allow it to be disabled and this would realistically be a different configuration that …
=> Configurable banner capture/control session radius

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarInventoryUtil.java
While maintaining SW having the final say for inventories in SiegeZones.
____
____
____
=> Use Towny's keepinv event to provide better compatiblity with other plugins.

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownPeacefulnessUtil.java, src/main/resources/lang/en-US.yml
=> Fix peaceful towns being able to become the capital of a nation.

pom.xml, src/main/java/com/gmail/goosius/siegewar/enums/SiegeSide.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
____
```
- keep_inventory_on_siegezone_death.disable_for_defenders.enable
- Default: false
- This feature, when enabled, will cause defenders to not keep their inventory if the Siege point balance is too far positive.
- ie: They defenders are losing by a great number.
- keep_inventory_on_siegezone_death.disable_for_defenders.threshold
- Default: 500
- The threshold required to cause defenders to lose their inventory. If the Siege point balance is equal to or greater than this number
and disable_for_defenders is enabled, defenders will not keep their inventories.
```
____
Closes #919 
____
By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, …
=> Add option to punish defenders with inventory loss when they are losing by too many points.

src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java, src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/resources/lang/en-US.yml
This pull request aims to add an option to force players to either plunder or invade a nation. This is due to a possible exploit to plunder a nation and then invade them and tax them tons.
____
```
New Config Option: war.siege.switches.only_one_action_enabled
- Default: false
- If true, players can only either invade or plunder a town, not both.
- If false, players can perform both actions.
```
____
Closes #922
____ …
=> Add Option to force players to either Plunder or Invade a Town

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
____
```
- peaceful_towns.cannot_assign_military_ranks
- Default: true
- Prevents players in peaceful towns from being given ranks with military-rank-permission nodes.
- It is not recommended to set this to false.
```
____
Closes #933.
____
=> Add option for mayors of peaceful towns to be able to assign military ranks.

pom.xml, src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/resources/lang/en-US.yml
Can be during any siege, or during only active battle sessions.
____
New Config Nodes:
```
BATTLE_COMMANDERS_BLOCK_ASSIGNMENT_DURING_BATTLE_SESSIONS(
"battle_commanders.block_rank_assignment_during_active_battlesessions",
"false",
"",
"# If this value is true, then the ranks containing the
siegewar.nation.siege.startconquestsiege permission node",
"# cannot be assigned to players who are part of a siege with an
active battle session."),
BATTLE_COMMANDERS_BLOCK_ASSIGNMENT_DURING_SIEGES(
"battle_commanders.block_rank_assignment_during_sieges",
"false",
"",
"# If this value is true, then the ranks containing the
siegewar.nation.siege.startconquestsiege permission node",
"# cannot be assigned to players who are part of a siege."),
```
____
Closes #949.
____
By making this pull request, I …
=> Add the ability to block assigning ranks that allow players to become battle commanders during sieges.

src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSelfListener.java, src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/CosmeticUtil.java
beacon_markers.battle_session_only boolean key in the yaml allows players to make the fake beacons only show during an active battle session
____
beacon_markers.battle_session_only boolean key
____
____
=> Add option to display beacons only when the battle session is active

src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java, src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
makes it so players can choose if they want people to only be able to cap the banner from wilderness or not, defaults to true meaning players can only cap the banner if they're in wilderness (vanilla sw behavior)
____
war.siege.distances.banner_control_session_check_wilderness
____
____
=> Add the option to make timed point zone (banner control session) not require player stand in the wilderness.

src/main/java/com/gmail/goosius/siegewar/events/BannerControlSessionPreStartEvent.java, src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
This PR adds the missing `BannerControlSessionPreStartEvent` to cancel a new potential banner control session. 
____
N/A
____
N/A
____
=> Add banner control session pre start event

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java, src/main/resources/lang/en-US.yml
- With current code, apparently non-participants in the besieged town SOMETIMES get full war sickness, and sometimes they do not
- This PR fixes the issue, so that non-participants in the besieged town ALWAYS get full war sickness
____
N/A
____
Closes #893 
____
- [ N/A Hopefully too trivial ] I have tested this pull request for defects on a server. 
=> Fixed bug where non-participants could be in besieged town without full war-sickness

src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
- It seems better for playability to do warsickness only during battle sessions
- This PR does that
____
N/A
____
N/A
____
- [  N/A too trivial ] I have tested this pull request for defects on a server. 
=> Give war sickness only during battle sessions
